//this tables was generated by GNESCC
//source grammar:../../../Tests/GNESCC/regexp/complex/seq_in_cls_2/seq_in_cls_2.yrd
//date:11/4/2011 2:49:31 PM

module Yard.Generators.GNESCCGenerator.Tables_seq_in_cls_2

open Yard.Generators.GNESCCGenerator
open Yard.Generators.GNESCCGenerator.CommonTypes

type symbol =
    | T_PLUS
    | NT_s
    | NT_gnesccStart
let getTag smb =
    match smb with
    | T_PLUS -> 5
    | NT_s -> 4
    | NT_gnesccStart -> 2
let getName tag =
    match tag with
    | 5 -> T_PLUS
    | 4 -> NT_s
    | 2 -> NT_gnesccStart
    | _ -> failwith "getName: bad tag."
let prodToNTerm = 
  [| 1; 0 |];
let symbolIdx = 
  [| 1; 2; 1; 3; 0; 0 |];
let startKernelIdxs =  [0]
let isStart =
  [| [| true; true |];
     [| false; false |];
     [| false; false |];
     [| false; true |]; |]
let gotoTable =
  [| [| Some 1; None |];
     [| None; None |];
     [| None; None |];
     [| Some 2; None |]; |]
let actionTable = 
  [| [| [Reduce 1]; [Reduce 1]; [Reduce 1] |];
     [| [Shift 3]; [Accept]; [Accept] |];
     [| [Shift 3]; [Error]; [Error] |];
     [| [Reduce 1]; [Reduce 1]; [Reduce 1] |]; |]
let tables = 
  {StartIdx=startKernelIdxs
   SymbolIdx=symbolIdx
   GotoTable=gotoTable
   ActionTable=actionTable
   IsStart=isStart
   ProdToNTerm=prodToNTerm}
