//this tables was generated by GNESCC
//source grammar:left_implicit.yrd
//date:20.12.2011 17:44:13

module Yard.Generators.GNESCCGenerator.Tables_left_implicit

open Yard.Generators.GNESCCGenerator
open Yard.Generators.GNESCCGenerator.CommonTypes

type symbol =
    | T_C
    | T_A
    | NT_b
    | NT_s
    | NT_gnesccStart
let getTag smb =
    match smb with
    | T_C -> 7
    | T_A -> 6
    | NT_b -> 5
    | NT_s -> 4
    | NT_gnesccStart -> 2
let getName tag =
    match tag with
    | 7 -> T_C
    | 6 -> T_A
    | 5 -> NT_b
    | 4 -> NT_s
    | 2 -> NT_gnesccStart
    | _ -> failwith "getName: bad tag."
let prodToNTerm = 
  [| 2; 1; 0 |];
let symbolIdx = 
  [| 2; 3; 2; 3; 1; 0; 1; 0 |];
let startKernelIdxs =  [0]
let isStart =
  [| [| true; true; true |];
     [| false; false; false |];
     [| false; false; false |];
     [| false; true; true |];
     [| false; false; false |];
     [| false; false; false |];
     [| false; false; false |]; |]
let gotoTable =
  [| [| Some 3; Some 1; None |];
     [| None; None; None |];
     [| None; None; None |];
     [| Some 3; Some 2; None |];
     [| None; None; None |];
     [| None; None; None |];
     [| None; None; None |]; |]
let actionTable = 
  [| [| [Shift 6]; [Shift 4]; [Error]; [Error] |];
     [| [Accept]; [Shift 5]; [Accept]; [Accept] |];
     [| [Error]; [Shift 5]; [Error]; [Error] |];
     [| [Shift 6]; [Shift 4]; [Error]; [Error] |];
     [| [Reduce 1]; [Reduce 1]; [Reduce 1]; [Reduce 1] |];
     [| [Reduce 1]; [Reduce 1]; [Reduce 1]; [Reduce 1] |];
     [| [Reduce 2]; [Reduce 2]; [Reduce 2]; [Reduce 2] |]; |]
let tables = 
  {StartIdx=startKernelIdxs
   SymbolIdx=symbolIdx
   GotoTable=gotoTable
   ActionTable=actionTable
   IsStart=isStart
   ProdToNTerm=prodToNTerm}
