image: Visual Studio 2017

init:
  - git config --global core.autocrlf input
install:
  - git submodule update --init --recursive
build_script:
  - cmd: build.cmd
test: off
version: 0.0.1.{build}
artifacts:
  - path: bin
    name: bin
