/// Implementation file for parser generated by the fsyacc-compatibility backend for fsharpyacc.
module ParserSLR1

#nowarn "64" // turn off warnings that type variables used in production annotations are instantiated to concrete type

open Microsoft.FSharp.Text.Lexing
open Microsoft.FSharp.Text.Parsing.ParseHelpers

// This type is the type of tokens accepted by the parser
type token =
    | EOF of (int)
    | MULT of (int)
    | PLUS of (int)
    | S of (int)
    | Z of (int)

/// This type is used to give symbolic names to token indexes, useful for error messages.
type private tokenId =
    | TOKEN_EOF
    | TOKEN_MULT
    | TOKEN_PLUS
    | TOKEN_S
    | TOKEN_Z
    | TOKEN_end_of_input
    | TOKEN_error

/// This type is used to give symbolic names to token indexes, useful for error messages.
type private nonterminalId =
    | NONTERM__starts
    | NONTERM_b
    | NONTERM_expr
    | NONTERM_s

/// Maps tokens to integer indexes.
let private tagOfToken = function
    | EOF _ -> 0
    | MULT _ -> 1
    | PLUS _ -> 2
    | S _ -> 3
    | Z _ -> 4

/// Maps integer indices to symbolic token ids.
let private tokenTagToTokenId = function
    | 0 -> TOKEN_EOF
    | 1 -> TOKEN_MULT
    | 2 -> TOKEN_PLUS
    | 3 -> TOKEN_S
    | 4 -> TOKEN_Z
    | 6 -> TOKEN_end_of_input
    | 5 -> TOKEN_error
    | tokenIdx ->
        failwithf "tokenTagToTokenId: Invalid token. (Tag = %i)" tokenIdx

/// Maps production indexes returned in syntax errors to strings representing
/// the non-terminal that would be produced by that production.
let private prodIdxToNonTerminal = function
    | 0 -> NONTERM__starts
    | 1 -> NONTERM_b
    | 2 -> NONTERM_b
    | 3 -> NONTERM_expr
    | 4 -> NONTERM_expr
    | 5 -> NONTERM_expr
    | 6 -> NONTERM_s
    | prodIdx ->
        failwithf "prodIdxToNonTerminal: Invalid production index. (Index = %i)" prodIdx

let [<Literal>] private _fsyacc_endOfInputTag = 6
let [<Literal>] private _fsyacc_tagOfErrorTerminal = 5

/// Gets the name of a token as a string.
let token_to_string = function
    | EOF _ -> "EOF"
    | MULT _ -> "MULT"
    | PLUS _ -> "PLUS"
    | S _ -> "S"
    | Z _ -> "Z"

/// Gets the data carried by a token as an object.
let private _fsyacc_dataOfToken = function
    | EOF _fsyacc_x -> box _fsyacc_x
    | MULT _fsyacc_x -> box _fsyacc_x
    | PLUS _fsyacc_x -> box _fsyacc_x
    | S _fsyacc_x -> box _fsyacc_x
    | Z _fsyacc_x -> box _fsyacc_x

let private _fsyacc_gotos = [| 0us; 65535us; 3us; 65535us; 0us; 4us; 6us; 9us; 7us; 10us; 1us; 65535us; 0us; 5us; 1us; 65535us; 0us; 1us; |]
let private _fsyacc_sparseGotoTableRowOffsets = [| 0us; 1us; 5us; 7us; |]
let private _fsyacc_stateToProdIdxsTableElements = [| 7us; 0us; 2us; 1us; 5us; 3us; 4us; 6us; 1us; 0us; 1us; 2us; 1us; 1us; 1us; 5us; 3us; 3us; 4us; 6us; 3us; 2us; 1us; 3us; 3us; 2us; 1us; 4us; 1us; 6us; 1us; 3us; 1us; 4us; |]
let private _fsyacc_stateToProdIdxsTableRowOffsets = [| 0us; 8us; 10us; 12us; 14us; 16us; 20us; 24us; 28us; 30us; 32us; |]
let [<Literal>] private _fsyacc_action_rows = 11
let private _fsyacc_actionTableElements = [| 2us; 32768us; 3us; 2us; 4us; 3us; 1us; 32768us; 6us; 49152us; 3us; 32768us; 0us; 16386us; 1us; 16386us; 2us; 16386us; 3us; 32768us; 0us; 16385us; 1us; 16385us; 2us; 16385us; 3us; 32768us; 0us; 16389us; 1us; 16389us; 2us; 16389us; 3us; 32768us; 0us; 8us; 1us; 6us; 2us; 7us; 2us; 32768us; 3us; 2us; 4us; 3us; 2us; 32768us; 3us; 2us; 4us; 3us; 1us; 32768us; 6us; 16390us; 3us; 32768us; 0us; 16387us; 1us; 16387us; 2us; 16387us; 3us; 32768us; 0us; 16388us; 1us; 16388us; 2us; 16388us; |]
let private _fsyacc_actionTableRowOffsets = [| 0us; 3us; 5us; 9us; 13us; 17us; 21us; 24us; 27us; 29us; 33us; |]
let private _fsyacc_reductionSymbolCounts = [| 1us; 1us; 1us; 3us; 3us; 1us; 2us; |]
let private _fsyacc_productionToNonTerminalTable = [| 0us; 1us; 1us; 2us; 2us; 2us; 3us; |]
let private _fsyacc_immediateActions = [| 65535us; 49152us; 16386us; 16385us; 16389us; 65535us; 65535us; 65535us; 16390us; 16387us; 16388us; |]
let private _fsyacc_reductions () = [|
    (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
        let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : _)) in
        Microsoft.FSharp.Core.Operators.box
            (
                (
                    raise (Microsoft.FSharp.Text.Parsing.Accept (Microsoft.FSharp.Core.Operators.box _1))
                )
            : '_starts))
    (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
        let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
        Microsoft.FSharp.Core.Operators.box
            (
                (
                    0 
                )
            : 'b))
    (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
        let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
        Microsoft.FSharp.Core.Operators.box
            (
                (
                    1 
                )
            : 'b))
    (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
        let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'expr)) in
        let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
        let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'b)) in
        Microsoft.FSharp.Core.Operators.box
            (
                (
                    _1 * _3 
                )
            : 'expr))
    (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
        let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'expr)) in
        let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
        let _3 = (let data = parseState.GetInput(3) in (Microsoft.FSharp.Core.Operators.unbox data : 'b)) in
        Microsoft.FSharp.Core.Operators.box
            (
                (
                    _1 + _3 
                )
            : 'expr))
    (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
        let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'b)) in
        Microsoft.FSharp.Core.Operators.box
            (
                (
                    _1 
                )
            : 'expr))
    (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
        let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'expr)) in
        let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : int)) in
        Microsoft.FSharp.Core.Operators.box
            (
                (
                    _1
                )
            : _))
    |]

let tables () : Microsoft.FSharp.Text.Parsing.Tables<_> = {
    reductions = _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken;
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError =
        (fun (ctxt : Microsoft.FSharp.Text.Parsing.ParseErrorContext<_>) ->
            match parse_error_rich with
            | Some f -> f ctxt
            | None -> parse_error ctxt.Message);
    numTerminals = 7;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable;
    }
    
let engine lexer lexbuf startState =
    (tables ()).Interpret(lexer, lexbuf, startState)

let s lexer lexbuf : _ =
    unbox ((tables ()).Interpret(lexer, lexbuf, 0))

