ALTER TABLE JRXML_REPORT_IMAGES ADD (JRI_ADLER32 VARCHAR2(30));

ALTER TABLE JRXML_REPORT_IMAGES ADD (JRI_ADLER32_VALID  VARCHAR2(1)  DEFAULT 'N' NOT NULL);

ALTER TABLE JRXML_REPORT_IMAGES ADD CONSTRAINT JRI_ALER32_CK CHECK (JRI_ADLER32_VALID IN ('Y', 'N')) ENABLE;

CREATE OR REPLACE TRIGGER TRG_JRI_BRUI 
BEFORE INSERT OR UPDATE ON JRXML_REPORT_IMAGES 
FOR EACH ROW 
BEGIN
  IF INSERTING THEN 
    :NEW.JRI_ADLER32_VALID:='N';
  ELSE
    IF     :OLD.JRI_ADLER32_VALID='Y'
       AND :NEW.JRI_ADLER32_VALID='Y' THEN
      :NEW.JRI_ADLER32_VALID:='N';
    END IF;
  END IF;
END;
/