CREATE TABLE JRXML_LOGGING (
  JRL_ID                  NUMBER NOT NULL,
  JRL_RUN_ID              NUMBER NOT NULL,
  JRL_TIME                TIMESTAMP NOT NULL,
  JRL_TIME_SINCE_LAST_LOG NUMBER NOT NULL,
  JRL_TEXT                VARCHAR2(4000)
);

ALTER TABLE JRXML_LOGGING ADD CONSTRAINT JRL_PK PRIMARY KEY (JRL_ID);
