--------------------------------------------------------
--  DDL for Table JRXML_RESOURCE_FILES
--------------------------------------------------------

CREATE TABLE JRXML_RESOURCE_FILES
  (	JRR_ID      NUMBER NOT NULL, 
	JRR_NAME    VARCHAR2(80) NOT NULL, 
    JRR_LOCALE  VARCHAR2(10), 
	JRR_VALID   VARCHAR2(1)  NOT NULL,
	JRR_CONTENT CLOB         NOT NULL
  );


--------------------------------------------------------
--  Constraints for Table JRXML_RESOURCE_FILES
--------------------------------------------------------

ALTER TABLE JRXML_RESOURCE_FILES ADD CONSTRAINT JRR_VALID_CK CHECK (JRR_VALID IN ('Y', 'N')) ENABLE;


ALTER TABLE JRXML_RESOURCE_FILES ADD CONSTRAINT JRR_UK UNIQUE (JRR_NAME, JRR_LOCALE);


ALTER TABLE JRXML_RESOURCE_FILES ADD CONSTRAINT JRR_PK PRIMARY KEY (JRR_ID);


CREATE OR REPLACE TRIGGER TRG_JRR_BRUI 
BEFORE INSERT OR UPDATE ON JRXML_RESOURCE_FILES 
FOR EACH ROW 
BEGIN
  IF INSERTING THEN 
    :NEW.JRR_VALID:='N';
  ELSE
    IF     :OLD.JRR_VALID='Y'
       AND :NEW.JRR_VALID='Y' THEN
      :NEW.JRR_VALID:='N';
    END IF;
  END IF;
END;
/