--------------------------------------------------------
--  DDL for Table JRXML_NLS_PARAMETERS
--------------------------------------------------------

CREATE TABLE JRXML_NLS_PARAMETERS
  (	JRN_ID                   NUMBER(38)   NOT NULL,   
    JRN_LOCALE_LANGUAGE      VARCHAR2(10) NOT NULL,   
	JRN_LOCALE_COUNTRY       VARCHAR2(10),   
	JRN_NLS_LANGUAGE         VARCHAR2(80) NOT NULL,   
	JRN_NLS_TERRITORY        VARCHAR2(80) NOT NULL,   
	JRN_NUMERIC_CHARACTERS   VARCHAR2(02) NOT NULL,   
	JRN_DEFAULT_DATE_FORMAT  VARCHAR2(80) NOT NULL,      
	JRN_SHORT_DATE_FORMAT    VARCHAR2(80) NOT NULL,      
	JRN_MEDIUM_DATE_FORMAT   VARCHAR2(80) NOT NULL,      
	JRN_LONG_DATE_FORMAT     VARCHAR2(80) NOT NULL,       
	JRN_DEFAULT_TIME_FORMAT  VARCHAR2(80) NOT NULL,      
	JRN_SHORT_TIME_FORMAT    VARCHAR2(80) NOT NULL,      
	JRN_MEDIUM_TIME_FORMAT   VARCHAR2(80) NOT NULL,      
	JRN_LONG_TIME_FORMAT     VARCHAR2(80) NOT NULL,     
	JRN_DATE_TIME_STRING     VARCHAR2(10) NOT NULL,     
	JRN_CURRENCY             VARCHAR2(10) NOT NULL 
  ) 
;

--------------------------------------------------------
--  Constraints for Table JRXML_NLS_PARAMETERS
--------------------------------------------------------

ALTER TABLE JRXML_NLS_PARAMETERS ADD CONSTRAINT JRN_PK PRIMARY KEY(JRN_ID);

ALTER TABLE JRXML_NLS_PARAMETERS ADD CONSTRAINT JRN_UK UNIQUE (JRN_LOCALE_LANGUAGE, JRN_LOCALE_COUNTRY);



