SET SCAN OFF
SET TIMING ON

PROMPT install tables

@JRXML_RESOURCE_FILES.sql
@JRXML_RESOURCE_ENTRIES.sql
@JRXML_NLS_PARAMETERS.sql

PROMPT install packages
@AS_PDF3_MOD.pls
@PK_JRXML2PDF_LOG.pls
@PK_JRXML2PDF_UTIL.pls
@PK_JRXML2PDF_REPGEN.pls

PROMPT install NLS-seed-data
@INSERT_NLS_DATA.sql

PROMPT finished

