SET SCAN OFF
SET TIMING ON

PROMPT Create and Alter tables
@JRXML_APEX2PDF_TEMPLATES.sql
@ALTER_JRXML_REPORT_IMAGES.sql

PROMPT install packages
@AS_PDF3_MOD.pls
@PK_JRXML2PDF_LOG.pls
@PK_JRXML2PDF_TYPES.pls
@PK_JRXML2PDF_UTIL.pls
@PK_JRXML2PDF_CHARTS.pls
@PK_JRXML2PDF_LOADER.pls
@PK_JRXML2PDF_REPGEN.pls
@PK_JRXML2PDF_APEX2JRXML.pls

PROMPT Install template data
@INSERT_TEMPLATES.sql
PROMPT finished

