//this tables was generated by RACC
//source grammar:..\Tests\RACC\test_opt\\test_opt.yrd
//date:2/7/2011 11:46:23

#light "off"
module Yard.Generators.RACCGenerator.Tables_Opt

open Yard.Generators.RACCGenerator

let autumataDict = 
dict [|("raccStart",{ 
   DIDToStateMap = dict [|(0,(State 0));(1,(State 1));(2,DummyState)|];
   DStartState   = 0;
   DFinaleStates = Set.ofArray [|1|];
   DRules        = Set.ofArray [|{ 
   FromStateID = 0;
   Symbol      = (DSymbol "s");
   Label       = Set.ofArray [|List.ofArray [|(FATrace (TSmbS 0))|]|];
   ToStateID   = 1;
}
;{ 
   FromStateID = 1;
   Symbol      = Dummy;
   Label       = Set.ofArray [|List.ofArray [|(FATrace (TSmbE 0))|]|];
   ToStateID   = 2;
}
|];
}
);("s",{ 
   DIDToStateMap = dict [|(0,(State 0));(1,(State 1));(2,(State 2));(3,DummyState);(4,DummyState)|];
   DStartState   = 0;
   DFinaleStates = Set.ofArray [|1;2|];
   DRules        = Set.ofArray [|{ 
   FromStateID = 0;
   Symbol      = (DSymbol "NUMBER");
   Label       = Set.ofArray [|List.ofArray [|(FATrace (TSeqS 5));(FATrace (TSmbS 1))|]|];
   ToStateID   = 1;
}
;{ 
   FromStateID = 1;
   Symbol      = (DSymbol "PLUS");
   Label       = Set.ofArray [|List.ofArray [|(FATrace (TSmbE 1));(FATrace (TOptS 2));(FATrace (TOptE 2));(FATrace (TSeqE 5))|];List.ofArray [|(FATrace (TSmbE 1));(FATrace (TOptS 2));(FATrace (TSeqS 4));(FATrace (TSmbS 3))|]|];
   ToStateID   = 2;
}
;{ 
   FromStateID = 1;
   Symbol      = Dummy;
   Label       = Set.ofArray [|List.ofArray [|(FATrace (TSmbE 1));(FATrace (TOptS 2));(FATrace (TOptE 2));(FATrace (TSeqE 5))|];List.ofArray [|(FATrace (TSmbE 1));(FATrace (TOptS 2));(FATrace (TSeqS 4));(FATrace (TSmbS 3))|]|];
   ToStateID   = 3;
}
;{ 
   FromStateID = 2;
   Symbol      = Dummy;
   Label       = Set.ofArray [|List.ofArray [|(FATrace (TSmbE 3));(FATrace (TSeqE 4));(FATrace (TOptE 2));(FATrace (TSeqE 5))|]|];
   ToStateID   = 4;
}
|];
}
)|]

let gotoSet = 
    Set.ofArray [|(-1239003080,Set.ofArray [|("raccStart",2)|]);(-1408241699,Set.ofArray [|("s",1)|]);(-635149922,Set.ofArray [|("raccStart",1)|]);(1800920813,Set.ofArray [|("s",3)|]);(1800920910,Set.ofArray [|("s",4)|]);(1904107720,Set.ofArray [|("s",1)|]);(452886726,Set.ofArray [|("s",2)|])|]
    |> dict
