//this file was generated by GNESCC
//source grammar:yards\a1.yrd
//date:11/15/2011 11:39:18 AM

module GNESCC.Actions

open Yard.Generators.GNESCCGenerator

let getUnmatched x expectedType =
    "Unexpected type of node\nType " + x.ToString() + " is not expected in this position\n" + expectedType + " was expected." |> failwith
let binop0 expr = 
    let inner  = 
        match expr with
        | REAlt(Some(x), None) -> 
            let yardLAltAction expr = 
                match expr with
                | RESeq [gnescc_x0] -> 
                    let (gnescc_x0) =
                        let yardElemAction expr = 
                            match expr with
                            | RELeaf tOP_PLUS_EQ -> tOP_PLUS_EQ :?> 'a
                            | x -> getUnmatched x "RELeaf"

                        yardElemAction(gnescc_x0)
                    (gnescc_x0 )
                | x -> getUnmatched x "RESeq"

            yardLAltAction x 
        | REAlt(None, Some(x)) -> 
            let yardRAltAction expr = 
                match expr with
                | REAlt(Some(x), None) -> 
                    let yardLAltAction expr = 
                        match expr with
                        | RESeq [gnescc_x0] -> 
                            let (gnescc_x0) =
                                let yardElemAction expr = 
                                    match expr with
                                    | RELeaf tOP_MINUS_EQ -> tOP_MINUS_EQ :?> 'a
                                    | x -> getUnmatched x "RELeaf"

                                yardElemAction(gnescc_x0)
                            (gnescc_x0 )
                        | x -> getUnmatched x "RESeq"

                    yardLAltAction x 
                | REAlt(None, Some(x)) -> 
                    let yardRAltAction expr = 
                        match expr with
                        | REAlt(Some(x), None) -> 
                            let yardLAltAction expr = 
                                match expr with
                                | RESeq [gnescc_x0] -> 
                                    let (gnescc_x0) =
                                        let yardElemAction expr = 
                                            match expr with
                                            | RELeaf tOP_MUL_EQ -> tOP_MUL_EQ :?> 'a
                                            | x -> getUnmatched x "RELeaf"

                                        yardElemAction(gnescc_x0)
                                    (gnescc_x0 )
                                | x -> getUnmatched x "RESeq"

                            yardLAltAction x 
                        | REAlt(None, Some(x)) -> 
                            let yardRAltAction expr = 
                                match expr with
                                | REAlt(Some(x), None) -> 
                                    let yardLAltAction expr = 
                                        match expr with
                                        | RESeq [gnescc_x0] -> 
                                            let (gnescc_x0) =
                                                let yardElemAction expr = 
                                                    match expr with
                                                    | RELeaf tOP_DIV_EQ -> tOP_DIV_EQ :?> 'a
                                                    | x -> getUnmatched x "RELeaf"

                                                yardElemAction(gnescc_x0)
                                            (gnescc_x0 )
                                        | x -> getUnmatched x "RESeq"

                                    yardLAltAction x 
                                | REAlt(None, Some(x)) -> 
                                    let yardRAltAction expr = 
                                        match expr with
                                        | REAlt(Some(x), None) -> 
                                            let yardLAltAction expr = 
                                                match expr with
                                                | RESeq [gnescc_x0] -> 
                                                    let (gnescc_x0) =
                                                        let yardElemAction expr = 
                                                            match expr with
                                                            | RELeaf tOP_MOD_EQ -> tOP_MOD_EQ :?> 'a
                                                            | x -> getUnmatched x "RELeaf"

                                                        yardElemAction(gnescc_x0)
                                                    (gnescc_x0 )
                                                | x -> getUnmatched x "RESeq"

                                            yardLAltAction x 
                                        | REAlt(None, Some(x)) -> 
                                            let yardRAltAction expr = 
                                                match expr with
                                                | REAlt(Some(x), None) -> 
                                                    let yardLAltAction expr = 
                                                        match expr with
                                                        | RESeq [gnescc_x0] -> 
                                                            let (gnescc_x0) =
                                                                let yardElemAction expr = 
                                                                    match expr with
                                                                    | RELeaf tOP_AND_EQ -> tOP_AND_EQ :?> 'a
                                                                    | x -> getUnmatched x "RELeaf"

                                                                yardElemAction(gnescc_x0)
                                                            (gnescc_x0 )
                                                        | x -> getUnmatched x "RESeq"

                                                    yardLAltAction x 
                                                | REAlt(None, Some(x)) -> 
                                                    let yardRAltAction expr = 
                                                        match expr with
                                                        | REAlt(Some(x), None) -> 
                                                            let yardLAltAction expr = 
                                                                match expr with
                                                                | RESeq [gnescc_x0] -> 
                                                                    let (gnescc_x0) =
                                                                        let yardElemAction expr = 
                                                                            match expr with
                                                                            | RELeaf tOP_XOR_EQ -> tOP_XOR_EQ :?> 'a
                                                                            | x -> getUnmatched x "RELeaf"

                                                                        yardElemAction(gnescc_x0)
                                                                    (gnescc_x0 )
                                                                | x -> getUnmatched x "RESeq"

                                                            yardLAltAction x 
                                                        | REAlt(None, Some(x)) -> 
                                                            let yardRAltAction expr = 
                                                                match expr with
                                                                | REAlt(Some(x), None) -> 
                                                                    let yardLAltAction expr = 
                                                                        match expr with
                                                                        | RESeq [gnescc_x0] -> 
                                                                            let (gnescc_x0) =
                                                                                let yardElemAction expr = 
                                                                                    match expr with
                                                                                    | RELeaf tOP_OR_EQ -> tOP_OR_EQ :?> 'a
                                                                                    | x -> getUnmatched x "RELeaf"

                                                                                yardElemAction(gnescc_x0)
                                                                            (gnescc_x0 )
                                                                        | x -> getUnmatched x "RESeq"

                                                                    yardLAltAction x 
                                                                | REAlt(None, Some(x)) -> 
                                                                    let yardRAltAction expr = 
                                                                        match expr with
                                                                        | REAlt(Some(x), None) -> 
                                                                            let yardLAltAction expr = 
                                                                                match expr with
                                                                                | RESeq [gnescc_x0] -> 
                                                                                    let (gnescc_x0) =
                                                                                        let yardElemAction expr = 
                                                                                            match expr with
                                                                                            | RELeaf tOP_EQ -> tOP_EQ :?> 'a
                                                                                            | x -> getUnmatched x "RELeaf"

                                                                                        yardElemAction(gnescc_x0)
                                                                                    (gnescc_x0 )
                                                                                | x -> getUnmatched x "RESeq"

                                                                            yardLAltAction x 
                                                                        | REAlt(None, Some(x)) -> 
                                                                            let yardRAltAction expr = 
                                                                                match expr with
                                                                                | REAlt(Some(x), None) -> 
                                                                                    let yardLAltAction expr = 
                                                                                        match expr with
                                                                                        | RESeq [gnescc_x0] -> 
                                                                                            let (gnescc_x0) =
                                                                                                let yardElemAction expr = 
                                                                                                    match expr with
                                                                                                    | RELeaf tOP_PLUS -> tOP_PLUS :?> 'a
                                                                                                    | x -> getUnmatched x "RELeaf"

                                                                                                yardElemAction(gnescc_x0)
                                                                                            (gnescc_x0 )
                                                                                        | x -> getUnmatched x "RESeq"

                                                                                    yardLAltAction x 
                                                                                | REAlt(None, Some(x)) -> 
                                                                                    let yardRAltAction expr = 
                                                                                        match expr with
                                                                                        | REAlt(Some(x), None) -> 
                                                                                            let yardLAltAction expr = 
                                                                                                match expr with
                                                                                                | RESeq [gnescc_x0] -> 
                                                                                                    let (gnescc_x0) =
                                                                                                        let yardElemAction expr = 
                                                                                                            match expr with
                                                                                                            | RELeaf tOP_MINUS -> tOP_MINUS :?> 'a
                                                                                                            | x -> getUnmatched x "RELeaf"

                                                                                                        yardElemAction(gnescc_x0)
                                                                                                    (gnescc_x0 )
                                                                                                | x -> getUnmatched x "RESeq"

                                                                                            yardLAltAction x 
                                                                                        | REAlt(None, Some(x)) -> 
                                                                                            let yardRAltAction expr = 
                                                                                                match expr with
                                                                                                | REAlt(Some(x), None) -> 
                                                                                                    let yardLAltAction expr = 
                                                                                                        match expr with
                                                                                                        | RESeq [gnescc_x0] -> 
                                                                                                            let (gnescc_x0) =
                                                                                                                let yardElemAction expr = 
                                                                                                                    match expr with
                                                                                                                    | RELeaf tOP_MUL -> tOP_MUL :?> 'a
                                                                                                                    | x -> getUnmatched x "RELeaf"

                                                                                                                yardElemAction(gnescc_x0)
                                                                                                            (gnescc_x0 )
                                                                                                        | x -> getUnmatched x "RESeq"

                                                                                                    yardLAltAction x 
                                                                                                | REAlt(None, Some(x)) -> 
                                                                                                    let yardRAltAction expr = 
                                                                                                        match expr with
                                                                                                        | REAlt(Some(x), None) -> 
                                                                                                            let yardLAltAction expr = 
                                                                                                                match expr with
                                                                                                                | RESeq [gnescc_x0] -> 
                                                                                                                    let (gnescc_x0) =
                                                                                                                        let yardElemAction expr = 
                                                                                                                            match expr with
                                                                                                                            | RELeaf tOP_DIV -> tOP_DIV :?> 'a
                                                                                                                            | x -> getUnmatched x "RELeaf"

                                                                                                                        yardElemAction(gnescc_x0)
                                                                                                                    (gnescc_x0 )
                                                                                                                | x -> getUnmatched x "RESeq"

                                                                                                            yardLAltAction x 
                                                                                                        | REAlt(None, Some(x)) -> 
                                                                                                            let yardRAltAction expr = 
                                                                                                                match expr with
                                                                                                                | REAlt(Some(x), None) -> 
                                                                                                                    let yardLAltAction expr = 
                                                                                                                        match expr with
                                                                                                                        | RESeq [gnescc_x0] -> 
                                                                                                                            let (gnescc_x0) =
                                                                                                                                let yardElemAction expr = 
                                                                                                                                    match expr with
                                                                                                                                    | RELeaf tOP_MOD -> tOP_MOD :?> 'a
                                                                                                                                    | x -> getUnmatched x "RELeaf"

                                                                                                                                yardElemAction(gnescc_x0)
                                                                                                                            (gnescc_x0 )
                                                                                                                        | x -> getUnmatched x "RESeq"

                                                                                                                    yardLAltAction x 
                                                                                                                | REAlt(None, Some(x)) -> 
                                                                                                                    let yardRAltAction expr = 
                                                                                                                        match expr with
                                                                                                                        | REAlt(Some(x), None) -> 
                                                                                                                            let yardLAltAction expr = 
                                                                                                                                match expr with
                                                                                                                                | RESeq [gnescc_x0] -> 
                                                                                                                                    let (gnescc_x0) =
                                                                                                                                        let yardElemAction expr = 
                                                                                                                                            match expr with
                                                                                                                                            | RELeaf tOP_TILDA -> tOP_TILDA :?> 'a
                                                                                                                                            | x -> getUnmatched x "RELeaf"

                                                                                                                                        yardElemAction(gnescc_x0)
                                                                                                                                    (gnescc_x0 )
                                                                                                                                | x -> getUnmatched x "RESeq"

                                                                                                                            yardLAltAction x 
                                                                                                                        | REAlt(None, Some(x)) -> 
                                                                                                                            let yardRAltAction expr = 
                                                                                                                                match expr with
                                                                                                                                | REAlt(Some(x), None) -> 
                                                                                                                                    let yardLAltAction expr = 
                                                                                                                                        match expr with
                                                                                                                                        | RESeq [gnescc_x0] -> 
                                                                                                                                            let (gnescc_x0) =
                                                                                                                                                let yardElemAction expr = 
                                                                                                                                                    match expr with
                                                                                                                                                    | RELeaf tOP_LT -> tOP_LT :?> 'a
                                                                                                                                                    | x -> getUnmatched x "RELeaf"

                                                                                                                                                yardElemAction(gnescc_x0)
                                                                                                                                            (gnescc_x0 )
                                                                                                                                        | x -> getUnmatched x "RESeq"

                                                                                                                                    yardLAltAction x 
                                                                                                                                | REAlt(None, Some(x)) -> 
                                                                                                                                    let yardRAltAction expr = 
                                                                                                                                        match expr with
                                                                                                                                        | REAlt(Some(x), None) -> 
                                                                                                                                            let yardLAltAction expr = 
                                                                                                                                                match expr with
                                                                                                                                                | RESeq [gnescc_x0] -> 
                                                                                                                                                    let (gnescc_x0) =
                                                                                                                                                        let yardElemAction expr = 
                                                                                                                                                            match expr with
                                                                                                                                                            | RELeaf tOP_MT -> tOP_MT :?> 'a
                                                                                                                                                            | x -> getUnmatched x "RELeaf"

                                                                                                                                                        yardElemAction(gnescc_x0)
                                                                                                                                                    (gnescc_x0 )
                                                                                                                                                | x -> getUnmatched x "RESeq"

                                                                                                                                            yardLAltAction x 
                                                                                                                                        | REAlt(None, Some(x)) -> 
                                                                                                                                            let yardRAltAction expr = 
                                                                                                                                                match expr with
                                                                                                                                                | REAlt(Some(x), None) -> 
                                                                                                                                                    let yardLAltAction expr = 
                                                                                                                                                        match expr with
                                                                                                                                                        | RESeq [gnescc_x0] -> 
                                                                                                                                                            let (gnescc_x0) =
                                                                                                                                                                let yardElemAction expr = 
                                                                                                                                                                    match expr with
                                                                                                                                                                    | RELeaf tOP_LT_EQ -> tOP_LT_EQ :?> 'a
                                                                                                                                                                    | x -> getUnmatched x "RELeaf"

                                                                                                                                                                yardElemAction(gnescc_x0)
                                                                                                                                                            (gnescc_x0 )
                                                                                                                                                        | x -> getUnmatched x "RESeq"

                                                                                                                                                    yardLAltAction x 
                                                                                                                                                | REAlt(None, Some(x)) -> 
                                                                                                                                                    let yardRAltAction expr = 
                                                                                                                                                        match expr with
                                                                                                                                                        | RESeq [gnescc_x0] -> 
                                                                                                                                                            let (gnescc_x0) =
                                                                                                                                                                let yardElemAction expr = 
                                                                                                                                                                    match expr with
                                                                                                                                                                    | RELeaf tOP_MT_EQ -> tOP_MT_EQ :?> 'a
                                                                                                                                                                    | x -> getUnmatched x "RELeaf"

                                                                                                                                                                yardElemAction(gnescc_x0)
                                                                                                                                                            (gnescc_x0 )
                                                                                                                                                        | x -> getUnmatched x "RESeq"

                                                                                                                                                    yardRAltAction x 
                                                                                                                                                | x -> getUnmatched x "REAlt"

                                                                                                                                            yardRAltAction x 
                                                                                                                                        | x -> getUnmatched x "REAlt"

                                                                                                                                    yardRAltAction x 
                                                                                                                                | x -> getUnmatched x "REAlt"

                                                                                                                            yardRAltAction x 
                                                                                                                        | x -> getUnmatched x "REAlt"

                                                                                                                    yardRAltAction x 
                                                                                                                | x -> getUnmatched x "REAlt"

                                                                                                            yardRAltAction x 
                                                                                                        | x -> getUnmatched x "REAlt"

                                                                                                    yardRAltAction x 
                                                                                                | x -> getUnmatched x "REAlt"

                                                                                            yardRAltAction x 
                                                                                        | x -> getUnmatched x "REAlt"

                                                                                    yardRAltAction x 
                                                                                | x -> getUnmatched x "REAlt"

                                                                            yardRAltAction x 
                                                                        | x -> getUnmatched x "REAlt"

                                                                    yardRAltAction x 
                                                                | x -> getUnmatched x "REAlt"

                                                            yardRAltAction x 
                                                        | x -> getUnmatched x "REAlt"

                                                    yardRAltAction x 
                                                | x -> getUnmatched x "REAlt"

                                            yardRAltAction x 
                                        | x -> getUnmatched x "REAlt"

                                    yardRAltAction x 
                                | x -> getUnmatched x "REAlt"

                            yardRAltAction x 
                        | x -> getUnmatched x "REAlt"

                    yardRAltAction x 
                | x -> getUnmatched x "REAlt"

            yardRAltAction x 
        | x -> getUnmatched x "REAlt"
    box (inner)
let sql_expr1 expr = 
    let inner  = 
        match expr with
        | REAlt(Some(x), None) -> 
            let yardLAltAction expr = 
                match expr with
                | RESeq [gnescc_x0] -> 
                    let (gnescc_x0) =
                        let yardElemAction expr = 
                            match expr with
                            | RELeaf tIDENT -> tIDENT :?> 'a
                            | x -> getUnmatched x "RELeaf"

                        yardElemAction(gnescc_x0)
                    (gnescc_x0 )
                | x -> getUnmatched x "RESeq"

            yardLAltAction x 
        | REAlt(None, Some(x)) -> 
            let yardRAltAction expr = 
                match expr with
                | REAlt(Some(x), None) -> 
                    let yardLAltAction expr = 
                        match expr with
                        | RESeq [gnescc_x0] -> 
                            let (gnescc_x0) =
                                let yardElemAction expr = 
                                    match expr with
                                    | RELeaf sql_value -> (sql_value :?> _ ) 
                                    | x -> getUnmatched x "RELeaf"

                                yardElemAction(gnescc_x0)
                            (gnescc_x0 )
                        | x -> getUnmatched x "RESeq"

                    yardLAltAction x 
                | REAlt(None, Some(x)) -> 
                    let yardRAltAction expr = 
                        match expr with
                        | REAlt(Some(x), None) -> 
                            let yardLAltAction expr = 
                                match expr with
                                | RESeq [gnescc_x0; gnescc_x1; gnescc_x2] -> 
                                    let (gnescc_x0) =
                                        let yardElemAction expr = 
                                            match expr with
                                            | RELeaf tLPAREN -> tLPAREN :?> 'a
                                            | x -> getUnmatched x "RELeaf"

                                        yardElemAction(gnescc_x0)
                                    let (gnescc_x1) =
                                        let yardElemAction expr = 
                                            match expr with
                                            | RELeaf sql_expr -> (sql_expr :?> _ ) 
                                            | x -> getUnmatched x "RELeaf"

                                        yardElemAction(gnescc_x1)
                                    let (gnescc_x2) =
                                        let yardElemAction expr = 
                                            match expr with
                                            | RELeaf tRPAREN -> tRPAREN :?> 'a
                                            | x -> getUnmatched x "RELeaf"

                                        yardElemAction(gnescc_x2)
                                    (gnescc_x0,gnescc_x1,gnescc_x2 )
                                | x -> getUnmatched x "RESeq"

                            yardLAltAction x 
                        | REAlt(None, Some(x)) -> 
                            let yardRAltAction expr = 
                                match expr with
                                | REAlt(Some(x), None) -> 
                                    let yardLAltAction expr = 
                                        match expr with
                                        | RESeq [gnescc_x0] -> 
                                            let (gnescc_x0) =
                                                let yardElemAction expr = 
                                                    match expr with
                                                    | RELeaf tLOCALVAR -> tLOCALVAR :?> 'a
                                                    | x -> getUnmatched x "RELeaf"

                                                yardElemAction(gnescc_x0)
                                            (gnescc_x0 )
                                        | x -> getUnmatched x "RESeq"

                                    yardLAltAction x 
                                | REAlt(None, Some(x)) -> 
                                    let yardRAltAction expr = 
                                        match expr with
                                        | REAlt(Some(x), None) -> 
                                            let yardLAltAction expr = 
                                                match expr with
                                                | RESeq [gnescc_x0; gnescc_x1; gnescc_x2] -> 
                                                    let (gnescc_x2) =
                                                        let yardElemAction expr = 
                                                            match expr with
                                                            | RELeaf sql_expr -> (sql_expr :?> _ ) 
                                                            | x -> getUnmatched x "RELeaf"

                                                        yardElemAction(gnescc_x2)
                                                    let (gnescc_x1) =
                                                        let yardElemAction expr = 
                                                            match expr with
                                                            | RELeaf binop -> (binop :?> _ ) 
                                                            | x -> getUnmatched x "RELeaf"

                                                        yardElemAction(gnescc_x1)
                                                    let (gnescc_x2) =
                                                        let yardElemAction expr = 
                                                            match expr with
                                                            | RELeaf sql_expr -> (sql_expr :?> _ ) 
                                                            | x -> getUnmatched x "RELeaf"

                                                        yardElemAction(gnescc_x2)
                                                    (gnescc_x0,gnescc_x1,gnescc_x2 )
                                                | x -> getUnmatched x "RESeq"

                                            yardLAltAction x 
                                        | REAlt(None, Some(x)) -> 
                                            let yardRAltAction expr = 
                                                match expr with
                                                | RESeq [gnescc_x0; gnescc_x1; gnescc_x2; gnescc_x3] -> 
                                                    let (gnescc_x0) =
                                                        let yardElemAction expr = 
                                                            match expr with
                                                            | RELeaf tKW_IF -> tKW_IF :?> 'a
                                                            | x -> getUnmatched x "RELeaf"

                                                        yardElemAction(gnescc_x0)
                                                    let (gnescc_x1) =
                                                        let yardElemAction expr = 
                                                            match expr with
                                                            | RELeaf sql_expr -> (sql_expr :?> _ ) 
                                                            | x -> getUnmatched x "RELeaf"

                                                        yardElemAction(gnescc_x1)
                                                    let (gnescc_x2) =
                                                        let yardElemAction expr = 
                                                            match expr with
                                                            | RELeaf tKW_THEN -> tKW_THEN :?> 'a
                                                            | x -> getUnmatched x "RELeaf"

                                                        yardElemAction(gnescc_x2)
                                                    let (gnescc_x3) =
                                                        let yardElemAction expr = 
                                                            match expr with
                                                            | REAlt(Some(x), None) -> 
                                                                let yardLAltAction expr = 
                                                                    match expr with
                                                                    | RESeq [gnescc_x0] -> 
                                                                        let (gnescc_x0) =
                                                                            let yardElemAction expr = 
                                                                                match expr with
                                                                                | RESeq [gnescc_x0; gnescc_x1; gnescc_x2] -> 
                                                                                    let (gnescc_x0) =
                                                                                        let yardElemAction expr = 
                                                                                            match expr with
                                                                                            | RELeaf tKW_BEGIN -> tKW_BEGIN :?> 'a
                                                                                            | x -> getUnmatched x "RELeaf"

                                                                                        yardElemAction(gnescc_x0)
                                                                                    let (gnescc_x1) =
                                                                                        let yardElemAction expr = 
                                                                                            match expr with
                                                                                            | REClosure(lst) -> 
                                                                                                let yardClsAction expr = 
                                                                                                    match expr with
                                                                                                    | RELeaf sql_expr -> (sql_expr :?> _ ) 
                                                                                                    | x -> getUnmatched x "RELeaf"

                                                                                                List.map yardClsAction lst 
                                                                                            | x -> getUnmatched x "REClosure"

                                                                                        yardElemAction(gnescc_x1)
                                                                                    let (gnescc_x2) =
                                                                                        let yardElemAction expr = 
                                                                                            match expr with
                                                                                            | RELeaf tKW_END -> tKW_END :?> 'a
                                                                                            | x -> getUnmatched x "RELeaf"

                                                                                        yardElemAction(gnescc_x2)
                                                                                    (gnescc_x0,gnescc_x1,gnescc_x2 )
                                                                                | x -> getUnmatched x "RESeq"

                                                                            yardElemAction(gnescc_x0)
                                                                        (gnescc_x0 )
                                                                    | x -> getUnmatched x "RESeq"

                                                                yardLAltAction x 
                                                            | REAlt(None, Some(x)) -> 
                                                                let yardRAltAction expr = 
                                                                    match expr with
                                                                    | RESeq [gnescc_x0] -> 
                                                                        let (gnescc_x0) =
                                                                            let yardElemAction expr = 
                                                                                match expr with
                                                                                | RELeaf sql_expr -> (sql_expr :?> _ ) 
                                                                                | x -> getUnmatched x "RELeaf"

                                                                            yardElemAction(gnescc_x0)
                                                                        (gnescc_x0 )
                                                                    | x -> getUnmatched x "RESeq"

                                                                yardRAltAction x 
                                                            | x -> getUnmatched x "REAlt"

                                                        yardElemAction(gnescc_x3)
                                                    (gnescc_x0,gnescc_x1,gnescc_x2,gnescc_x3 )
                                                | x -> getUnmatched x "RESeq"

                                            yardRAltAction x 
                                        | x -> getUnmatched x "REAlt"

                                    yardRAltAction x 
                                | x -> getUnmatched x "REAlt"

                            yardRAltAction x 
                        | x -> getUnmatched x "REAlt"

                    yardRAltAction x 
                | x -> getUnmatched x "REAlt"

            yardRAltAction x 
        | x -> getUnmatched x "REAlt"
    box (inner)
let sql_value2 expr = 
    let inner  = 
        match expr with
        | REAlt(Some(x), None) -> 
            let yardLAltAction expr = 
                match expr with
                | RESeq [gnescc_x0] -> 
                    let (gnescc_x0) =
                        let yardElemAction expr = 
                            match expr with
                            | RELeaf tSTRING_CONST -> tSTRING_CONST :?> 'a
                            | x -> getUnmatched x "RELeaf"

                        yardElemAction(gnescc_x0)
                    (gnescc_x0 )
                | x -> getUnmatched x "RESeq"

            yardLAltAction x 
        | REAlt(None, Some(x)) -> 
            let yardRAltAction expr = 
                match expr with
                | RESeq [gnescc_x0] -> 
                    let (gnescc_x0) =
                        let yardElemAction expr = 
                            match expr with
                            | RELeaf tDEC_NUMBER -> tDEC_NUMBER :?> 'a
                            | x -> getUnmatched x "RELeaf"

                        yardElemAction(gnescc_x0)
                    (gnescc_x0 )
                | x -> getUnmatched x "RESeq"

            yardRAltAction x 
        | x -> getUnmatched x "REAlt"
    box (inner)

let ruleToAction = dict [|(0,sql_value2); (2,sql_expr1); (3,binop0)|]

