 
module YC.JSONLexer

open Microsoft.FSharp.Collections
open YC.FST.GraphBasedFst
open YC.FST.AbstractLexing.Interpreter
open AbstractAnalysis.Common
open JSON.Parser
open System


let fstLexer () = 
   let startState = ResizeArray.singleton 0
   let finishState = ResizeArray.singleton 65535
   let transitions = new ResizeArray<_>()
   transitions.Add(0, new EdgeLbl<_,_>(Smbl (char 65535), Eps), 65535)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl '\t', Eps), 1)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl ' ', Eps), 1)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl '\"', Eps), 5)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl '-', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl '0', Eps), 2)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl '1', Eps), 3)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl '2', Eps), 3)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl '3', Eps), 3)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl '4', Eps), 3)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl '5', Eps), 3)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl '6', Eps), 3)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl '7', Eps), 3)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl '8', Eps), 3)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl '9', Eps), 3)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl '\t', Eps), 33)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl ' ', Eps), 33)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl '\"', Smbl 0), 5)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl '-', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl '0', Smbl 0), 2)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl '1', Smbl 0), 3)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl '2', Smbl 0), 3)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl '3', Smbl 0), 3)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl '4', Smbl 0), 3)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl '5', Smbl 0), 3)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl '6', Smbl 0), 3)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl '7', Smbl 0), 3)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl '8', Smbl 0), 3)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl '9', Smbl 0), 3)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 0), 65535)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl '\t', Eps), 1)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl ' ', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl '\"', Eps), 6)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl '-', Eps), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl '/', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl '0', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl '1', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl '2', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl '3', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl '4', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl '5', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl '6', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl '7', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl '8', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl '9', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'A', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'B', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'C', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'D', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'E', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'F', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'G', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'H', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'I', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'J', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'K', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'L', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'M', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'N', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'O', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'P', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'Q', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'R', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'S', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'T', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'U', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'V', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'W', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'X', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'Y', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'Z', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl '\\', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'a', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'b', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'c', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'd', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'e', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'f', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'g', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'h', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'i', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'j', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'k', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'l', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'm', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'n', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'o', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'p', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'q', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'r', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 's', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 't', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'u', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'v', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'w', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'x', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'y', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'z', Eps), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl (char 65535), Eps), 65535)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl '\t', Eps), 1)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl ' ', Eps), 1)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl '\"', Eps), 5)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl '-', Eps), 4)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl '0', Eps), 10)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl '1', Eps), 11)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl '2', Eps), 11)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl '3', Eps), 11)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl '4', Eps), 11)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl '5', Eps), 11)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl '6', Eps), 11)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl '7', Eps), 11)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl '8', Eps), 11)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl '9', Eps), 11)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl (char 65535), Eps), 65535)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl '\t', Smbl 1), 1)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl ' ', Smbl 1), 1)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl '\"', Smbl 1), 5)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl '-', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl '.', Eps), 13)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl '0', Eps), 32)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl '1', Eps), 32)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl '2', Eps), 32)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl '3', Eps), 32)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl '4', Eps), 32)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl '5', Eps), 32)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl '6', Eps), 32)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl '7', Eps), 32)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl '8', Eps), 32)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl '9', Eps), 32)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'E', Eps), 12)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'e', Eps), 12)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 1), 65535)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl '\t', Smbl 1), 1)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl ' ', Smbl 1), 1)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl '\"', Smbl 1), 5)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl '-', Smbl 1), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl '.', Eps), 13)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl '0', Eps), 27)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl '1', Eps), 28)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl '2', Eps), 28)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl '3', Eps), 28)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl '4', Eps), 28)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl '5', Eps), 28)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl '6', Eps), 28)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl '7', Eps), 28)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl '8', Eps), 28)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl '9', Eps), 28)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'E', Eps), 12)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'e', Eps), 12)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 1), 65535)
   transitions.Add(33, new EdgeLbl<_,_>(Smbl '\t', Eps), 33)
   transitions.Add(33, new EdgeLbl<_,_>(Smbl ' ', Eps), 33)
   transitions.Add(33, new EdgeLbl<_,_>(Smbl '\"', Smbl 0), 5)
   transitions.Add(33, new EdgeLbl<_,_>(Smbl '-', Smbl 0), 4)
   transitions.Add(33, new EdgeLbl<_,_>(Smbl '0', Smbl 0), 2)
   transitions.Add(33, new EdgeLbl<_,_>(Smbl '1', Smbl 0), 3)
   transitions.Add(33, new EdgeLbl<_,_>(Smbl '2', Smbl 0), 3)
   transitions.Add(33, new EdgeLbl<_,_>(Smbl '3', Smbl 0), 3)
   transitions.Add(33, new EdgeLbl<_,_>(Smbl '4', Smbl 0), 3)
   transitions.Add(33, new EdgeLbl<_,_>(Smbl '5', Smbl 0), 3)
   transitions.Add(33, new EdgeLbl<_,_>(Smbl '6', Smbl 0), 3)
   transitions.Add(33, new EdgeLbl<_,_>(Smbl '7', Smbl 0), 3)
   transitions.Add(33, new EdgeLbl<_,_>(Smbl '8', Smbl 0), 3)
   transitions.Add(33, new EdgeLbl<_,_>(Smbl '9', Smbl 0), 3)
   transitions.Add(33, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 0), 65535)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl '\t', Eps), 1)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl ' ', Eps), 1)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl '\"', Eps), 5)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl '-', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl '0', Eps), 19)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl '1', Eps), 19)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl '2', Eps), 19)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl '3', Eps), 19)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl '4', Eps), 19)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl '5', Eps), 19)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl '6', Eps), 19)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl '7', Eps), 19)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl '8', Eps), 19)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl '9', Eps), 19)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl (char 65535), Eps), 65535)
   transitions.Add(32, new EdgeLbl<_,_>(Smbl '\t', Smbl 1), 1)
   transitions.Add(32, new EdgeLbl<_,_>(Smbl ' ', Smbl 1), 1)
   transitions.Add(32, new EdgeLbl<_,_>(Smbl '\"', Smbl 1), 5)
   transitions.Add(32, new EdgeLbl<_,_>(Smbl '-', Smbl 1), 4)
   transitions.Add(32, new EdgeLbl<_,_>(Smbl '.', Eps), 13)
   transitions.Add(32, new EdgeLbl<_,_>(Smbl '0', Eps), 32)
   transitions.Add(32, new EdgeLbl<_,_>(Smbl '1', Eps), 32)
   transitions.Add(32, new EdgeLbl<_,_>(Smbl '2', Eps), 32)
   transitions.Add(32, new EdgeLbl<_,_>(Smbl '3', Eps), 32)
   transitions.Add(32, new EdgeLbl<_,_>(Smbl '4', Eps), 32)
   transitions.Add(32, new EdgeLbl<_,_>(Smbl '5', Eps), 32)
   transitions.Add(32, new EdgeLbl<_,_>(Smbl '6', Eps), 32)
   transitions.Add(32, new EdgeLbl<_,_>(Smbl '7', Eps), 32)
   transitions.Add(32, new EdgeLbl<_,_>(Smbl '8', Eps), 32)
   transitions.Add(32, new EdgeLbl<_,_>(Smbl '9', Eps), 32)
   transitions.Add(32, new EdgeLbl<_,_>(Smbl 'E', Eps), 12)
   transitions.Add(32, new EdgeLbl<_,_>(Smbl 'e', Eps), 12)
   transitions.Add(32, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 1), 65535)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl '\t', Eps), 1)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl ' ', Eps), 1)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl '\"', Eps), 5)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl '+', Eps), 23)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl '-', Eps), 23)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl '0', Eps), 22)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl '1', Eps), 22)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl '2', Eps), 22)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl '3', Eps), 22)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl '4', Eps), 22)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl '5', Eps), 22)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl '6', Eps), 22)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl '7', Eps), 22)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl '8', Eps), 22)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl '9', Eps), 22)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl (char 65535), Eps), 65535)
   transitions.Add(27, new EdgeLbl<_,_>(Smbl '\t', Smbl 1), 1)
   transitions.Add(27, new EdgeLbl<_,_>(Smbl ' ', Smbl 1), 1)
   transitions.Add(27, new EdgeLbl<_,_>(Smbl '\"', Smbl 1), 5)
   transitions.Add(27, new EdgeLbl<_,_>(Smbl '-', Smbl 1), 4)
   transitions.Add(27, new EdgeLbl<_,_>(Smbl '.', Eps), 13)
   transitions.Add(27, new EdgeLbl<_,_>(Smbl '0', Eps), 31)
   transitions.Add(27, new EdgeLbl<_,_>(Smbl '1', Eps), 31)
   transitions.Add(27, new EdgeLbl<_,_>(Smbl '2', Eps), 31)
   transitions.Add(27, new EdgeLbl<_,_>(Smbl '3', Eps), 31)
   transitions.Add(27, new EdgeLbl<_,_>(Smbl '4', Eps), 31)
   transitions.Add(27, new EdgeLbl<_,_>(Smbl '5', Eps), 31)
   transitions.Add(27, new EdgeLbl<_,_>(Smbl '6', Eps), 31)
   transitions.Add(27, new EdgeLbl<_,_>(Smbl '7', Eps), 31)
   transitions.Add(27, new EdgeLbl<_,_>(Smbl '8', Eps), 31)
   transitions.Add(27, new EdgeLbl<_,_>(Smbl '9', Eps), 31)
   transitions.Add(27, new EdgeLbl<_,_>(Smbl 'E', Eps), 12)
   transitions.Add(27, new EdgeLbl<_,_>(Smbl 'e', Eps), 12)
   transitions.Add(27, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 1), 65535)
   transitions.Add(28, new EdgeLbl<_,_>(Smbl '\t', Smbl 1), 1)
   transitions.Add(28, new EdgeLbl<_,_>(Smbl ' ', Smbl 1), 1)
   transitions.Add(28, new EdgeLbl<_,_>(Smbl '\"', Smbl 1), 5)
   transitions.Add(28, new EdgeLbl<_,_>(Smbl '-', Smbl 1), 4)
   transitions.Add(28, new EdgeLbl<_,_>(Smbl '.', Eps), 13)
   transitions.Add(28, new EdgeLbl<_,_>(Smbl '0', Eps), 29)
   transitions.Add(28, new EdgeLbl<_,_>(Smbl '1', Eps), 30)
   transitions.Add(28, new EdgeLbl<_,_>(Smbl '2', Eps), 30)
   transitions.Add(28, new EdgeLbl<_,_>(Smbl '3', Eps), 30)
   transitions.Add(28, new EdgeLbl<_,_>(Smbl '4', Eps), 30)
   transitions.Add(28, new EdgeLbl<_,_>(Smbl '5', Eps), 30)
   transitions.Add(28, new EdgeLbl<_,_>(Smbl '6', Eps), 30)
   transitions.Add(28, new EdgeLbl<_,_>(Smbl '7', Eps), 30)
   transitions.Add(28, new EdgeLbl<_,_>(Smbl '8', Eps), 30)
   transitions.Add(28, new EdgeLbl<_,_>(Smbl '9', Eps), 30)
   transitions.Add(28, new EdgeLbl<_,_>(Smbl 'E', Eps), 12)
   transitions.Add(28, new EdgeLbl<_,_>(Smbl 'e', Eps), 12)
   transitions.Add(28, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 1), 65535)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl '\t', Smbl 1), 1)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl ' ', Smbl 1), 1)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl '\"', Smbl 1), 5)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl '-', Smbl 1), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl '.', Eps), 13)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl '0', Eps), 26)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl '1', Eps), 26)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl '2', Eps), 26)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl '3', Eps), 26)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl '4', Eps), 26)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl '5', Eps), 26)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl '6', Eps), 26)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl '7', Eps), 26)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl '8', Eps), 26)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl '9', Eps), 26)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'E', Eps), 12)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'e', Eps), 12)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 1), 65535)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl '\t', Smbl 1), 1)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl ' ', Smbl 1), 1)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl '\"', Smbl 1), 5)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl '-', Smbl 1), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl '.', Eps), 13)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl '0', Eps), 14)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl '1', Eps), 15)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl '2', Eps), 15)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl '3', Eps), 15)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl '4', Eps), 15)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl '5', Eps), 15)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl '6', Eps), 15)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl '7', Eps), 15)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl '8', Eps), 15)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl '9', Eps), 15)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'E', Eps), 12)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'e', Eps), 12)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 1), 65535)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl '\t', Eps), 1)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl ' ', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl '\"', Eps), 8)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl '-', Eps), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl '/', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl '0', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl '1', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl '2', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl '3', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl '4', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl '5', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl '6', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl '7', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl '8', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl '9', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'A', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'B', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'C', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'D', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'E', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'F', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'G', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'H', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'I', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'J', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'K', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'L', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'M', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'N', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'O', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'P', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'Q', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'R', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'S', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'T', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'U', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'V', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'W', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'X', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'Y', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'Z', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl '\\', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'a', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'b', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'c', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'd', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'e', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'f', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'g', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'h', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'i', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'j', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'k', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'l', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'm', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'n', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'o', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'p', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'q', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'r', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 's', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 't', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'u', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'v', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'w', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'x', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'y', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'z', Eps), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl (char 65535), Eps), 65535)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl '\t', Smbl 2), 1)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl ' ', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl '\"', Eps), 8)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl '-', Smbl 2), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl '/', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl '0', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl '1', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl '2', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl '3', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl '4', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl '5', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl '6', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl '7', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl '8', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl '9', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'A', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'B', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'C', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'D', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'E', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'F', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'G', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'H', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'I', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'J', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'K', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'L', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'M', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'N', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'O', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'P', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'Q', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'R', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'S', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'T', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'U', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'V', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'W', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'X', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'Y', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'Z', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl '\\', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'a', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'b', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'c', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'd', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'e', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'f', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'g', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'h', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'i', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'j', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'k', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'l', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'm', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'n', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'o', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'p', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'q', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'r', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 's', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 't', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'u', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'v', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'w', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'x', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'y', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'z', Eps), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 2), 65535)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl '\t', Eps), 1)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl ' ', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl '\"', Eps), 8)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl '-', Eps), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl '/', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl '0', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl '1', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl '2', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl '3', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl '4', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl '5', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl '6', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl '7', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl '8', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl '9', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'A', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'B', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'C', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'D', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'E', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'F', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'G', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'H', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'I', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'J', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'K', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'L', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'M', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'N', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'O', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'P', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'Q', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'R', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'S', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'T', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'U', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'V', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'W', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'X', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'Y', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'Z', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl '\\', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'a', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'b', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'c', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'd', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'e', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'f', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'g', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'h', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'i', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'j', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'k', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'l', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'm', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'n', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'o', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'p', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'q', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'r', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 's', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 't', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'u', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'v', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'w', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'x', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'y', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'z', Eps), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl (char 65535), Eps), 65535)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl '\t', Smbl 2), 1)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl ' ', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl '\"', Eps), 8)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl '-', Smbl 2), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl '/', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl '0', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl '1', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl '2', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl '3', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl '4', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl '5', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl '6', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl '7', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl '8', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl '9', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'A', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'B', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'C', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'D', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'E', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'F', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'G', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'H', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'I', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'J', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'K', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'L', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'M', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'N', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'O', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'P', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'Q', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'R', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'S', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'T', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'U', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'V', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'W', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'X', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'Y', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'Z', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl '\\', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'a', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'b', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'c', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'd', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'e', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'f', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'g', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'h', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'i', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'j', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'k', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'l', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'm', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'n', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'o', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'p', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'q', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'r', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 's', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 't', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'u', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'v', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'w', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'x', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'y', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'z', Eps), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 2), 65535)
   transitions.Add(26, new EdgeLbl<_,_>(Smbl '\t', Smbl 1), 1)
   transitions.Add(26, new EdgeLbl<_,_>(Smbl ' ', Smbl 1), 1)
   transitions.Add(26, new EdgeLbl<_,_>(Smbl '\"', Smbl 1), 5)
   transitions.Add(26, new EdgeLbl<_,_>(Smbl '-', Smbl 1), 4)
   transitions.Add(26, new EdgeLbl<_,_>(Smbl '.', Eps), 13)
   transitions.Add(26, new EdgeLbl<_,_>(Smbl '0', Eps), 26)
   transitions.Add(26, new EdgeLbl<_,_>(Smbl '1', Eps), 26)
   transitions.Add(26, new EdgeLbl<_,_>(Smbl '2', Eps), 26)
   transitions.Add(26, new EdgeLbl<_,_>(Smbl '3', Eps), 26)
   transitions.Add(26, new EdgeLbl<_,_>(Smbl '4', Eps), 26)
   transitions.Add(26, new EdgeLbl<_,_>(Smbl '5', Eps), 26)
   transitions.Add(26, new EdgeLbl<_,_>(Smbl '6', Eps), 26)
   transitions.Add(26, new EdgeLbl<_,_>(Smbl '7', Eps), 26)
   transitions.Add(26, new EdgeLbl<_,_>(Smbl '8', Eps), 26)
   transitions.Add(26, new EdgeLbl<_,_>(Smbl '9', Eps), 26)
   transitions.Add(26, new EdgeLbl<_,_>(Smbl 'E', Eps), 12)
   transitions.Add(26, new EdgeLbl<_,_>(Smbl 'e', Eps), 12)
   transitions.Add(26, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 1), 65535)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl '\t', Smbl 1), 1)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl ' ', Smbl 1), 1)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl '\"', Smbl 1), 5)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl '-', Smbl 1), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl '.', Eps), 13)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl '0', Eps), 18)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl '1', Eps), 18)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl '2', Eps), 18)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl '3', Eps), 18)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl '4', Eps), 18)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl '5', Eps), 18)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl '6', Eps), 18)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl '7', Eps), 18)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl '8', Eps), 18)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl '9', Eps), 18)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'E', Eps), 12)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'e', Eps), 12)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 1), 65535)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl '\t', Smbl 1), 1)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl ' ', Smbl 1), 1)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl '\"', Smbl 1), 5)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl '-', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl '.', Eps), 13)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl '0', Eps), 16)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl '1', Eps), 17)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl '2', Eps), 17)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl '3', Eps), 17)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl '4', Eps), 17)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl '5', Eps), 17)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl '6', Eps), 17)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl '7', Eps), 17)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl '8', Eps), 17)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl '9', Eps), 17)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'E', Eps), 12)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'e', Eps), 12)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 1), 65535)
   transitions.Add(23, new EdgeLbl<_,_>(Smbl '\t', Eps), 1)
   transitions.Add(23, new EdgeLbl<_,_>(Smbl ' ', Eps), 1)
   transitions.Add(23, new EdgeLbl<_,_>(Smbl '\"', Eps), 5)
   transitions.Add(23, new EdgeLbl<_,_>(Smbl '-', Eps), 4)
   transitions.Add(23, new EdgeLbl<_,_>(Smbl '0', Eps), 22)
   transitions.Add(23, new EdgeLbl<_,_>(Smbl '1', Eps), 22)
   transitions.Add(23, new EdgeLbl<_,_>(Smbl '2', Eps), 22)
   transitions.Add(23, new EdgeLbl<_,_>(Smbl '3', Eps), 22)
   transitions.Add(23, new EdgeLbl<_,_>(Smbl '4', Eps), 22)
   transitions.Add(23, new EdgeLbl<_,_>(Smbl '5', Eps), 22)
   transitions.Add(23, new EdgeLbl<_,_>(Smbl '6', Eps), 22)
   transitions.Add(23, new EdgeLbl<_,_>(Smbl '7', Eps), 22)
   transitions.Add(23, new EdgeLbl<_,_>(Smbl '8', Eps), 22)
   transitions.Add(23, new EdgeLbl<_,_>(Smbl '9', Eps), 22)
   transitions.Add(23, new EdgeLbl<_,_>(Smbl (char 65535), Eps), 65535)
   transitions.Add(22, new EdgeLbl<_,_>(Smbl '\t', Smbl 1), 1)
   transitions.Add(22, new EdgeLbl<_,_>(Smbl ' ', Smbl 1), 1)
   transitions.Add(22, new EdgeLbl<_,_>(Smbl '\"', Smbl 1), 5)
   transitions.Add(22, new EdgeLbl<_,_>(Smbl '-', Smbl 1), 4)
   transitions.Add(22, new EdgeLbl<_,_>(Smbl '0', Eps), 24)
   transitions.Add(22, new EdgeLbl<_,_>(Smbl '1', Eps), 24)
   transitions.Add(22, new EdgeLbl<_,_>(Smbl '2', Eps), 24)
   transitions.Add(22, new EdgeLbl<_,_>(Smbl '3', Eps), 24)
   transitions.Add(22, new EdgeLbl<_,_>(Smbl '4', Eps), 24)
   transitions.Add(22, new EdgeLbl<_,_>(Smbl '5', Eps), 24)
   transitions.Add(22, new EdgeLbl<_,_>(Smbl '6', Eps), 24)
   transitions.Add(22, new EdgeLbl<_,_>(Smbl '7', Eps), 24)
   transitions.Add(22, new EdgeLbl<_,_>(Smbl '8', Eps), 24)
   transitions.Add(22, new EdgeLbl<_,_>(Smbl '9', Eps), 24)
   transitions.Add(22, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 1), 65535)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl '\t', Smbl 1), 1)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl ' ', Smbl 1), 1)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl '\"', Smbl 1), 5)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl '-', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl '0', Eps), 20)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl '1', Eps), 20)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl '2', Eps), 20)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl '3', Eps), 20)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl '4', Eps), 20)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl '5', Eps), 20)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl '6', Eps), 20)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl '7', Eps), 20)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl '8', Eps), 20)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl '9', Eps), 20)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'E', Eps), 12)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'e', Eps), 12)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 1), 65535)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl '\t', Smbl 1), 1)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl ' ', Smbl 1), 1)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl '\"', Smbl 1), 5)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl '-', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl '.', Eps), 13)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl '0', Eps), 18)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl '1', Eps), 18)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl '2', Eps), 18)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl '3', Eps), 18)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl '4', Eps), 18)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl '5', Eps), 18)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl '6', Eps), 18)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl '7', Eps), 18)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl '8', Eps), 18)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl '9', Eps), 18)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'E', Eps), 12)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'e', Eps), 12)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 1), 65535)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl '\t', Smbl 1), 1)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl ' ', Smbl 1), 1)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl '\"', Smbl 1), 5)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl '-', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl '.', Eps), 13)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl '0', Eps), 18)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl '1', Eps), 18)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl '2', Eps), 18)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl '3', Eps), 18)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl '4', Eps), 18)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl '5', Eps), 18)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl '6', Eps), 18)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl '7', Eps), 18)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl '8', Eps), 18)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl '9', Eps), 18)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'E', Eps), 12)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'e', Eps), 12)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 1), 65535)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl '\t', Smbl 1), 1)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl ' ', Smbl 1), 1)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl '\"', Smbl 1), 5)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl '-', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl '.', Eps), 13)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl '0', Eps), 16)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl '1', Eps), 17)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl '2', Eps), 17)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl '3', Eps), 17)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl '4', Eps), 17)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl '5', Eps), 17)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl '6', Eps), 17)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl '7', Eps), 17)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl '8', Eps), 17)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl '9', Eps), 17)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'E', Eps), 12)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'e', Eps), 12)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 1), 65535)
   transitions.Add(20, new EdgeLbl<_,_>(Smbl '\t', Smbl 1), 1)
   transitions.Add(20, new EdgeLbl<_,_>(Smbl ' ', Smbl 1), 1)
   transitions.Add(20, new EdgeLbl<_,_>(Smbl '\"', Smbl 1), 5)
   transitions.Add(20, new EdgeLbl<_,_>(Smbl '-', Smbl 1), 4)
   transitions.Add(20, new EdgeLbl<_,_>(Smbl '0', Eps), 21)
   transitions.Add(20, new EdgeLbl<_,_>(Smbl '1', Eps), 21)
   transitions.Add(20, new EdgeLbl<_,_>(Smbl '2', Eps), 21)
   transitions.Add(20, new EdgeLbl<_,_>(Smbl '3', Eps), 21)
   transitions.Add(20, new EdgeLbl<_,_>(Smbl '4', Eps), 21)
   transitions.Add(20, new EdgeLbl<_,_>(Smbl '5', Eps), 21)
   transitions.Add(20, new EdgeLbl<_,_>(Smbl '6', Eps), 21)
   transitions.Add(20, new EdgeLbl<_,_>(Smbl '7', Eps), 21)
   transitions.Add(20, new EdgeLbl<_,_>(Smbl '8', Eps), 21)
   transitions.Add(20, new EdgeLbl<_,_>(Smbl '9', Eps), 21)
   transitions.Add(20, new EdgeLbl<_,_>(Smbl 'E', Eps), 12)
   transitions.Add(20, new EdgeLbl<_,_>(Smbl 'e', Eps), 12)
   transitions.Add(20, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 1), 65535)
   transitions.Add(21, new EdgeLbl<_,_>(Smbl '\t', Smbl 1), 1)
   transitions.Add(21, new EdgeLbl<_,_>(Smbl ' ', Smbl 1), 1)
   transitions.Add(21, new EdgeLbl<_,_>(Smbl '\"', Smbl 1), 5)
   transitions.Add(21, new EdgeLbl<_,_>(Smbl '-', Smbl 1), 4)
   transitions.Add(21, new EdgeLbl<_,_>(Smbl '0', Eps), 21)
   transitions.Add(21, new EdgeLbl<_,_>(Smbl '1', Eps), 21)
   transitions.Add(21, new EdgeLbl<_,_>(Smbl '2', Eps), 21)
   transitions.Add(21, new EdgeLbl<_,_>(Smbl '3', Eps), 21)
   transitions.Add(21, new EdgeLbl<_,_>(Smbl '4', Eps), 21)
   transitions.Add(21, new EdgeLbl<_,_>(Smbl '5', Eps), 21)
   transitions.Add(21, new EdgeLbl<_,_>(Smbl '6', Eps), 21)
   transitions.Add(21, new EdgeLbl<_,_>(Smbl '7', Eps), 21)
   transitions.Add(21, new EdgeLbl<_,_>(Smbl '8', Eps), 21)
   transitions.Add(21, new EdgeLbl<_,_>(Smbl '9', Eps), 21)
   transitions.Add(21, new EdgeLbl<_,_>(Smbl 'E', Eps), 12)
   transitions.Add(21, new EdgeLbl<_,_>(Smbl 'e', Eps), 12)
   transitions.Add(21, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 1), 65535)
   transitions.Add(24, new EdgeLbl<_,_>(Smbl '\t', Smbl 1), 1)
   transitions.Add(24, new EdgeLbl<_,_>(Smbl ' ', Smbl 1), 1)
   transitions.Add(24, new EdgeLbl<_,_>(Smbl '\"', Smbl 1), 5)
   transitions.Add(24, new EdgeLbl<_,_>(Smbl '-', Smbl 1), 4)
   transitions.Add(24, new EdgeLbl<_,_>(Smbl '0', Eps), 25)
   transitions.Add(24, new EdgeLbl<_,_>(Smbl '1', Eps), 25)
   transitions.Add(24, new EdgeLbl<_,_>(Smbl '2', Eps), 25)
   transitions.Add(24, new EdgeLbl<_,_>(Smbl '3', Eps), 25)
   transitions.Add(24, new EdgeLbl<_,_>(Smbl '4', Eps), 25)
   transitions.Add(24, new EdgeLbl<_,_>(Smbl '5', Eps), 25)
   transitions.Add(24, new EdgeLbl<_,_>(Smbl '6', Eps), 25)
   transitions.Add(24, new EdgeLbl<_,_>(Smbl '7', Eps), 25)
   transitions.Add(24, new EdgeLbl<_,_>(Smbl '8', Eps), 25)
   transitions.Add(24, new EdgeLbl<_,_>(Smbl '9', Eps), 25)
   transitions.Add(24, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 1), 65535)
   transitions.Add(25, new EdgeLbl<_,_>(Smbl '\t', Smbl 1), 1)
   transitions.Add(25, new EdgeLbl<_,_>(Smbl ' ', Smbl 1), 1)
   transitions.Add(25, new EdgeLbl<_,_>(Smbl '\"', Smbl 1), 5)
   transitions.Add(25, new EdgeLbl<_,_>(Smbl '-', Smbl 1), 4)
   transitions.Add(25, new EdgeLbl<_,_>(Smbl '0', Eps), 25)
   transitions.Add(25, new EdgeLbl<_,_>(Smbl '1', Eps), 25)
   transitions.Add(25, new EdgeLbl<_,_>(Smbl '2', Eps), 25)
   transitions.Add(25, new EdgeLbl<_,_>(Smbl '3', Eps), 25)
   transitions.Add(25, new EdgeLbl<_,_>(Smbl '4', Eps), 25)
   transitions.Add(25, new EdgeLbl<_,_>(Smbl '5', Eps), 25)
   transitions.Add(25, new EdgeLbl<_,_>(Smbl '6', Eps), 25)
   transitions.Add(25, new EdgeLbl<_,_>(Smbl '7', Eps), 25)
   transitions.Add(25, new EdgeLbl<_,_>(Smbl '8', Eps), 25)
   transitions.Add(25, new EdgeLbl<_,_>(Smbl '9', Eps), 25)
   transitions.Add(25, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 1), 65535)
   transitions.Add(31, new EdgeLbl<_,_>(Smbl '\t', Smbl 1), 1)
   transitions.Add(31, new EdgeLbl<_,_>(Smbl ' ', Smbl 1), 1)
   transitions.Add(31, new EdgeLbl<_,_>(Smbl '\"', Smbl 1), 5)
   transitions.Add(31, new EdgeLbl<_,_>(Smbl '-', Smbl 1), 4)
   transitions.Add(31, new EdgeLbl<_,_>(Smbl '.', Eps), 13)
   transitions.Add(31, new EdgeLbl<_,_>(Smbl '0', Eps), 31)
   transitions.Add(31, new EdgeLbl<_,_>(Smbl '1', Eps), 31)
   transitions.Add(31, new EdgeLbl<_,_>(Smbl '2', Eps), 31)
   transitions.Add(31, new EdgeLbl<_,_>(Smbl '3', Eps), 31)
   transitions.Add(31, new EdgeLbl<_,_>(Smbl '4', Eps), 31)
   transitions.Add(31, new EdgeLbl<_,_>(Smbl '5', Eps), 31)
   transitions.Add(31, new EdgeLbl<_,_>(Smbl '6', Eps), 31)
   transitions.Add(31, new EdgeLbl<_,_>(Smbl '7', Eps), 31)
   transitions.Add(31, new EdgeLbl<_,_>(Smbl '8', Eps), 31)
   transitions.Add(31, new EdgeLbl<_,_>(Smbl '9', Eps), 31)
   transitions.Add(31, new EdgeLbl<_,_>(Smbl 'E', Eps), 12)
   transitions.Add(31, new EdgeLbl<_,_>(Smbl 'e', Eps), 12)
   transitions.Add(31, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 1), 65535)
   transitions.Add(29, new EdgeLbl<_,_>(Smbl '\t', Smbl 1), 1)
   transitions.Add(29, new EdgeLbl<_,_>(Smbl ' ', Smbl 1), 1)
   transitions.Add(29, new EdgeLbl<_,_>(Smbl '\"', Smbl 1), 5)
   transitions.Add(29, new EdgeLbl<_,_>(Smbl '-', Smbl 1), 4)
   transitions.Add(29, new EdgeLbl<_,_>(Smbl '.', Eps), 13)
   transitions.Add(29, new EdgeLbl<_,_>(Smbl '0', Eps), 31)
   transitions.Add(29, new EdgeLbl<_,_>(Smbl '1', Eps), 31)
   transitions.Add(29, new EdgeLbl<_,_>(Smbl '2', Eps), 31)
   transitions.Add(29, new EdgeLbl<_,_>(Smbl '3', Eps), 31)
   transitions.Add(29, new EdgeLbl<_,_>(Smbl '4', Eps), 31)
   transitions.Add(29, new EdgeLbl<_,_>(Smbl '5', Eps), 31)
   transitions.Add(29, new EdgeLbl<_,_>(Smbl '6', Eps), 31)
   transitions.Add(29, new EdgeLbl<_,_>(Smbl '7', Eps), 31)
   transitions.Add(29, new EdgeLbl<_,_>(Smbl '8', Eps), 31)
   transitions.Add(29, new EdgeLbl<_,_>(Smbl '9', Eps), 31)
   transitions.Add(29, new EdgeLbl<_,_>(Smbl 'E', Eps), 12)
   transitions.Add(29, new EdgeLbl<_,_>(Smbl 'e', Eps), 12)
   transitions.Add(29, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 1), 65535)
   transitions.Add(30, new EdgeLbl<_,_>(Smbl '\t', Smbl 1), 1)
   transitions.Add(30, new EdgeLbl<_,_>(Smbl ' ', Smbl 1), 1)
   transitions.Add(30, new EdgeLbl<_,_>(Smbl '\"', Smbl 1), 5)
   transitions.Add(30, new EdgeLbl<_,_>(Smbl '-', Smbl 1), 4)
   transitions.Add(30, new EdgeLbl<_,_>(Smbl '.', Eps), 13)
   transitions.Add(30, new EdgeLbl<_,_>(Smbl '0', Eps), 29)
   transitions.Add(30, new EdgeLbl<_,_>(Smbl '1', Eps), 30)
   transitions.Add(30, new EdgeLbl<_,_>(Smbl '2', Eps), 30)
   transitions.Add(30, new EdgeLbl<_,_>(Smbl '3', Eps), 30)
   transitions.Add(30, new EdgeLbl<_,_>(Smbl '4', Eps), 30)
   transitions.Add(30, new EdgeLbl<_,_>(Smbl '5', Eps), 30)
   transitions.Add(30, new EdgeLbl<_,_>(Smbl '6', Eps), 30)
   transitions.Add(30, new EdgeLbl<_,_>(Smbl '7', Eps), 30)
   transitions.Add(30, new EdgeLbl<_,_>(Smbl '8', Eps), 30)
   transitions.Add(30, new EdgeLbl<_,_>(Smbl '9', Eps), 30)
   transitions.Add(30, new EdgeLbl<_,_>(Smbl 'E', Eps), 12)
   transitions.Add(30, new EdgeLbl<_,_>(Smbl 'e', Eps), 12)
   transitions.Add(30, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 1), 65535)
   new FST<_,_>(startState, finishState, transitions)

let actions () =
   [|

      (fun (gr : GraphTokenValue<_>) ->
                               None );
      (fun (gr : GraphTokenValue<_>) ->
                          NUMBER(gr) |> Some );
      (fun (gr : GraphTokenValue<_>) ->
                           STRING1(gr) |> Some );

   |]


let alphabet () = 
 new HashSet<_>([| Smbl (char 65535); Smbl '\t'; Smbl ' '; Smbl '\"'; Smbl '-'; Smbl '0'; Smbl '1'; Smbl '2'; Smbl '3'; Smbl '4'; Smbl '5'; Smbl '6'; Smbl '7'; Smbl '8'; Smbl '9'; Smbl '/'; Smbl 'A'; Smbl 'B'; Smbl 'C'; Smbl 'D'; Smbl 'E'; Smbl 'F'; Smbl 'G'; Smbl 'H'; Smbl 'I'; Smbl 'J'; Smbl 'K'; Smbl 'L'; Smbl 'M'; Smbl 'N'; Smbl 'O'; Smbl 'P'; Smbl 'Q'; Smbl 'R'; Smbl 'S'; Smbl 'T'; Smbl 'U'; Smbl 'V'; Smbl 'W'; Smbl 'X'; Smbl 'Y'; Smbl 'Z'; Smbl '\\'; Smbl 'a'; Smbl 'b'; Smbl 'c'; Smbl 'd'; Smbl 'e'; Smbl 'f'; Smbl 'g'; Smbl 'h'; Smbl 'i'; Smbl 'j'; Smbl 'k'; Smbl 'l'; Smbl 'm'; Smbl 'n'; Smbl 'o'; Smbl 'p'; Smbl 'q'; Smbl 'r'; Smbl 's'; Smbl 't'; Smbl 'u'; Smbl 'v'; Smbl 'w'; Smbl 'x'; Smbl 'y'; Smbl 'z'; Smbl '.'; Smbl '+';|])

let tokenize eof approximation = Tokenize (fstLexer()) (actions()) (alphabet()) eof approximation
