rm -rvf yc
mkdir yc
cp ../YaccConstructor/YaccConstructor/bin/Debug/*.dll yc
cp ../YaccConstructor/YaccConstructor/bin/Debug/*.exe yc
cp ../YaccConstructor/CYK/bin/Debug/*.exe yc
cp ../YaccConstructor/GLLGenerator/bin/Debug/*.dll yc
cp ../YaccConstructor/CYK/bin/Debug/*.dll yc
cp ../YaccConstructor/RNGLRCommon/bin/Debug/*.dll yc
cp ../YaccConstructor/RNGLRParser/bin/Debug/*.dll yc
cp ../YaccConstructor/RNGLRGenerator/bin/Debug/*.dll yc
cp ../YaccConstructor/Constraints/bin/Debug/*.dll yc
cp ../YaccConstructor/Utils.SourceText/bin/Debug/*.dll yc
cp ../YaccConstructor/FsYARD/bin/Debug/*.exe yc
cp ../YaccConstructor/FsYARD/bin/Debug/*.targets yc
cp ../YaccConstructor/AbstractLexer.Generator/bin/Debug/*.exe yc
cp ../YaccConstructor/AbstractLexer.Common/bin/Debug/*.dll yc
cp ../YaccConstructor/AbstractLexer.Core/bin/Debug/*.dll yc
cp ../YaccConstructor/AbstractParsing.Common/bin/Debug/*.dll yc
cp ../YaccConstructor/RNGLRAbstractParser/bin/Debug/*.dll yc


cp ../YaccConstructor/YaccConstructor/bin/Debug/*.mdb yc
cp ../YaccConstructor/GLLGenerator/bin/Debug/*.mdb yc
cp ../YaccConstructor/CYK/bin/Debug/*.mdb yc
cp ../YaccConstructor/RNGLRCommon/bin/Debug/*.mdb yc
cp ../YaccConstructor/RNGLRParser/bin/Debug/*.mdb yc
cp ../YaccConstructor/RNGLRGenerator/bin/Debug/*.mdb yc
cp ../YaccConstructor/Constraints/bin/Debug/*.mdb yc
cp ../YaccConstructor/Utils.SourceText/bin/Debug/*.mdb yc
cp ../YaccConstructor/FsYARD/bin/Debug/*.mdb yc
cp ../YaccConstructor/AbstractLexer.Generator/bin/Debug/*.mdb yc
cp ../YaccConstructor/AbstractLexer.Common/bin/Debug/*.mdb yc
cp ../YaccConstructor/AbstractLexer.Core/bin/Debug/*.mdb yc
cp ../YaccConstructor/AbstractParsing.Common/bin/Debug/*.mdb yc
cp ../YaccConstructor/RNGLRAbstractParser/bin/Debug/*.mdb yc

cp ../YaccConstructor/YaccConstructor/bin/Debug/*.pdb yc
cp ../YaccConstructor/GLLGenerator/bin/Debug/*.pdb yc
cp ../YaccConstructor/CYK/bin/Debug/*.pdb yc
cp ../YaccConstructor/RNGLRCommon/bin/Debug/*.pdb yc
cp ../YaccConstructor/RNGLRParser/bin/Debug/*.pdb yc
cp ../YaccConstructor/RNGLRGenerator/bin/Debug/*.pdb yc
cp ../YaccConstructor/Constraints/bin/Debug/*.pdb yc
cp ../YaccConstructor/Utils.SourceText/bin/Debug/*.pdb yc
cp ../YaccConstructor/FsYARD/bin/Debug/*.pdb yc
cp ../YaccConstructor/AbstractLexer.Generator/bin/Debug/*.pdb yc
cp ../YaccConstructor/AbstractLexer.Common/bin/Debug/*.pdb yc
cp ../YaccConstructor/AbstractLexer.Core/bin/Debug/*.pdb yc
cp ../YaccConstructor/AbstractParsing.Common/bin/Debug/*.pdb yc
cp ../YaccConstructor/RNGLRAbstractParser/bin/Debug/*.pdb yc
