 
module YC.ExtCalcLexer

open Microsoft.FSharp.Collections
open YC.FST.GraphBasedFst
open YC.FST.AbstractLexing.Interpreter
open AbstractAnalysis.Common
open ExtCalc.AbstractParser
open System.Collections.Generic
open YC.SDK.CommonInterfaces

let fstLexer () = 
   let startState = ResizeArray.singleton 0
   let finishState = ResizeArray.singleton 65535
   let transitions = new ResizeArray<_>()
   transitions.Add(0, new EdgeLbl<_,_>(Smbl (char 65535), Eps), 65535)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl '\t', Eps), 1)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl '\n', Eps), 1)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl '\r', Eps), 1)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl ' ', Eps), 1)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl '(', Eps), 7)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl ')', Eps), 8)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl '*', Eps), 11)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl '+', Eps), 10)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl '-', Eps), 3)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl '/', Eps), 9)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl '0', Eps), 2)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl '1', Eps), 2)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl '2', Eps), 2)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl '3', Eps), 2)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl '4', Eps), 2)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl '5', Eps), 2)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl '6', Eps), 2)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl '7', Eps), 2)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl '8', Eps), 2)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl '9', Eps), 2)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl ';', Eps), 6)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl '=', Eps), 5)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'A', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'B', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'C', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'D', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'E', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'F', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'G', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'H', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'I', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'J', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'K', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'L', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'M', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'N', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'O', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'P', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'Q', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'R', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'S', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'T', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'U', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'V', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'W', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'X', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'Y', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'Z', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'a', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'b', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'c', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'd', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'e', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'f', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'g', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'h', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'i', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'j', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'k', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'l', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'm', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'n', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'o', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'p', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'q', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'r', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 's', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 't', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'u', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'v', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'w', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'x', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'y', Eps), 4)
   transitions.Add(0, new EdgeLbl<_,_>(Smbl 'z', Eps), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl '\t', Smbl 0), 1)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl '\n', Smbl 0), 1)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl '\r', Smbl 0), 1)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl ' ', Smbl 0), 1)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl '(', Smbl 0), 7)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl ')', Smbl 0), 8)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl '*', Smbl 0), 11)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl '+', Smbl 0), 10)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl '-', Smbl 0), 3)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl '/', Smbl 0), 9)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl '0', Smbl 0), 2)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl '1', Smbl 0), 2)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl '2', Smbl 0), 2)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl '3', Smbl 0), 2)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl '4', Smbl 0), 2)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl '5', Smbl 0), 2)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl '6', Smbl 0), 2)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl '7', Smbl 0), 2)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl '8', Smbl 0), 2)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl '9', Smbl 0), 2)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl ';', Smbl 0), 6)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl '=', Smbl 0), 5)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'A', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'B', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'C', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'D', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'E', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'F', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'G', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'H', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'I', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'J', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'K', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'L', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'M', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'N', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'O', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'P', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'Q', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'R', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'S', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'T', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'U', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'V', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'W', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'X', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'Y', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'Z', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'a', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'b', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'c', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'd', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'e', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'f', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'g', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'h', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'i', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'j', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'k', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'l', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'm', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'n', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'o', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'p', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'q', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'r', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 's', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 't', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'u', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'v', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'w', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'x', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'y', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl 'z', Smbl 0), 4)
   transitions.Add(1, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 0), 65535)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl '\t', Smbl 6), 1)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl '\n', Smbl 6), 1)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl '\r', Smbl 6), 1)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl ' ', Smbl 6), 1)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl '(', Smbl 6), 7)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl ')', Smbl 6), 8)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl '*', Smbl 6), 11)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl '+', Smbl 6), 10)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl '-', Smbl 6), 3)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl '/', Smbl 6), 9)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl '0', Smbl 6), 2)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl '1', Smbl 6), 2)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl '2', Smbl 6), 2)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl '3', Smbl 6), 2)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl '4', Smbl 6), 2)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl '5', Smbl 6), 2)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl '6', Smbl 6), 2)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl '7', Smbl 6), 2)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl '8', Smbl 6), 2)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl '9', Smbl 6), 2)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl ';', Smbl 6), 6)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl '=', Smbl 6), 5)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'A', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'B', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'C', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'D', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'E', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'F', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'G', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'H', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'I', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'J', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'K', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'L', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'M', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'N', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'O', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'P', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'Q', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'R', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'S', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'T', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'U', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'V', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'W', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'X', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'Y', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'Z', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'a', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'b', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'c', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'd', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'e', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'f', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'g', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'h', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'i', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'j', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'k', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'l', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'm', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'n', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'o', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'p', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'q', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'r', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 's', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 't', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'u', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'v', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'w', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'x', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'y', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl 'z', Smbl 6), 4)
   transitions.Add(7, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 6), 65535)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl '\t', Smbl 7), 1)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl '\n', Smbl 7), 1)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl '\r', Smbl 7), 1)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl ' ', Smbl 7), 1)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl '(', Smbl 7), 7)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl ')', Smbl 7), 8)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl '*', Smbl 7), 11)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl '+', Smbl 7), 10)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl '-', Smbl 7), 3)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl '/', Smbl 7), 9)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl '0', Smbl 7), 2)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl '1', Smbl 7), 2)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl '2', Smbl 7), 2)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl '3', Smbl 7), 2)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl '4', Smbl 7), 2)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl '5', Smbl 7), 2)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl '6', Smbl 7), 2)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl '7', Smbl 7), 2)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl '8', Smbl 7), 2)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl '9', Smbl 7), 2)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl ';', Smbl 7), 6)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl '=', Smbl 7), 5)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'A', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'B', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'C', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'D', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'E', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'F', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'G', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'H', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'I', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'J', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'K', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'L', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'M', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'N', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'O', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'P', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'Q', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'R', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'S', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'T', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'U', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'V', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'W', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'X', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'Y', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'Z', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'a', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'b', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'c', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'd', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'e', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'f', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'g', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'h', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'i', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'j', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'k', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'l', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'm', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'n', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'o', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'p', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'q', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'r', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 's', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 't', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'u', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'v', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'w', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'x', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'y', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl 'z', Smbl 7), 4)
   transitions.Add(8, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 7), 65535)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl '\t', Smbl 10), 1)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl '\n', Smbl 10), 1)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl '\r', Smbl 10), 1)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl ' ', Smbl 10), 1)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl '(', Smbl 10), 7)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl ')', Smbl 10), 8)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl '*', Smbl 10), 11)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl '+', Smbl 10), 10)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl '-', Smbl 10), 3)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl '/', Smbl 10), 9)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl '0', Smbl 10), 2)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl '1', Smbl 10), 2)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl '2', Smbl 10), 2)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl '3', Smbl 10), 2)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl '4', Smbl 10), 2)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl '5', Smbl 10), 2)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl '6', Smbl 10), 2)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl '7', Smbl 10), 2)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl '8', Smbl 10), 2)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl '9', Smbl 10), 2)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl ';', Smbl 10), 6)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl '=', Smbl 10), 5)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'A', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'B', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'C', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'D', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'E', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'F', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'G', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'H', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'I', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'J', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'K', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'L', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'M', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'N', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'O', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'P', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'Q', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'R', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'S', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'T', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'U', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'V', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'W', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'X', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'Y', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'Z', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'a', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'b', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'c', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'd', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'e', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'f', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'g', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'h', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'i', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'j', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'k', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'l', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'm', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'n', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'o', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'p', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'q', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'r', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 's', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 't', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'u', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'v', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'w', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'x', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'y', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl 'z', Smbl 10), 4)
   transitions.Add(11, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 10), 65535)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl '\t', Smbl 9), 1)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl '\n', Smbl 9), 1)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl '\r', Smbl 9), 1)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl ' ', Smbl 9), 1)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl '(', Smbl 9), 7)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl ')', Smbl 9), 8)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl '*', Smbl 9), 11)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl '+', Smbl 9), 10)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl '-', Smbl 9), 3)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl '/', Smbl 9), 9)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl '0', Smbl 9), 2)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl '1', Smbl 9), 2)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl '2', Smbl 9), 2)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl '3', Smbl 9), 2)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl '4', Smbl 9), 2)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl '5', Smbl 9), 2)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl '6', Smbl 9), 2)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl '7', Smbl 9), 2)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl '8', Smbl 9), 2)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl '9', Smbl 9), 2)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl ';', Smbl 9), 6)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl '=', Smbl 9), 5)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'A', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'B', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'C', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'D', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'E', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'F', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'G', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'H', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'I', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'J', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'K', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'L', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'M', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'N', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'O', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'P', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'Q', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'R', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'S', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'T', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'U', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'V', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'W', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'X', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'Y', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'Z', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'a', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'b', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'c', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'd', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'e', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'f', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'g', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'h', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'i', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'j', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'k', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'l', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'm', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'n', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'o', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'p', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'q', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'r', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 's', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 't', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'u', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'v', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'w', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'x', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'y', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl 'z', Smbl 9), 4)
   transitions.Add(10, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 9), 65535)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl '\t', Smbl 5), 1)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl '\n', Smbl 5), 1)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl '\r', Smbl 5), 1)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl ' ', Smbl 5), 1)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl '(', Smbl 5), 7)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl ')', Smbl 5), 8)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl '*', Smbl 5), 11)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl '+', Smbl 5), 10)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl '-', Smbl 5), 3)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl '/', Smbl 5), 9)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl '0', Eps), 2)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl '1', Eps), 2)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl '2', Eps), 2)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl '3', Eps), 2)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl '4', Eps), 2)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl '5', Eps), 2)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl '6', Eps), 2)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl '7', Eps), 2)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl '8', Eps), 2)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl '9', Eps), 2)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl ';', Smbl 5), 6)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl '=', Smbl 5), 5)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'A', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'B', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'C', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'D', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'E', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'F', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'G', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'H', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'I', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'J', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'K', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'L', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'M', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'N', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'O', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'P', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'Q', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'R', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'S', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'T', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'U', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'V', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'W', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'X', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'Y', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'Z', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'a', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'b', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'c', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'd', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'e', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'f', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'g', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'h', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'i', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'j', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'k', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'l', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'm', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'n', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'o', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'p', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'q', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'r', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 's', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 't', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'u', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'v', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'w', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'x', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'y', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl 'z', Smbl 5), 4)
   transitions.Add(3, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 5), 65535)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl '\t', Smbl 8), 1)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl '\n', Smbl 8), 1)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl '\r', Smbl 8), 1)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl ' ', Smbl 8), 1)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl '(', Smbl 8), 7)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl ')', Smbl 8), 8)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl '*', Smbl 8), 11)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl '+', Smbl 8), 10)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl '-', Smbl 8), 3)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl '/', Smbl 8), 9)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl '0', Smbl 8), 2)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl '1', Smbl 8), 2)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl '2', Smbl 8), 2)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl '3', Smbl 8), 2)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl '4', Smbl 8), 2)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl '5', Smbl 8), 2)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl '6', Smbl 8), 2)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl '7', Smbl 8), 2)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl '8', Smbl 8), 2)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl '9', Smbl 8), 2)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl ';', Smbl 8), 6)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl '=', Smbl 8), 5)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'A', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'B', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'C', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'D', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'E', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'F', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'G', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'H', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'I', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'J', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'K', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'L', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'M', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'N', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'O', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'P', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'Q', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'R', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'S', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'T', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'U', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'V', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'W', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'X', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'Y', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'Z', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'a', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'b', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'c', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'd', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'e', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'f', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'g', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'h', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'i', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'j', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'k', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'l', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'm', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'n', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'o', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'p', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'q', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'r', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 's', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 't', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'u', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'v', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'w', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'x', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'y', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl 'z', Smbl 8), 4)
   transitions.Add(9, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 8), 65535)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl '\t', Smbl 1), 1)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl '\n', Smbl 1), 1)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl '\r', Smbl 1), 1)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl ' ', Smbl 1), 1)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl '(', Smbl 1), 7)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl ')', Smbl 1), 8)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl '*', Smbl 1), 11)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl '+', Smbl 1), 10)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl '-', Smbl 1), 3)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl '.', Eps), 14)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl '/', Smbl 1), 9)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl '0', Eps), 15)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl '1', Eps), 15)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl '2', Eps), 15)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl '3', Eps), 15)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl '4', Eps), 15)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl '5', Eps), 15)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl '6', Eps), 15)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl '7', Eps), 15)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl '8', Eps), 15)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl '9', Eps), 15)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl ';', Smbl 1), 6)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl '=', Smbl 1), 5)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'A', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'B', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'C', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'D', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'E', Eps), 13)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'F', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'G', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'H', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'I', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'J', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'K', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'L', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'M', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'N', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'O', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'P', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'Q', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'R', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'S', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'T', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'U', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'V', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'W', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'X', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'Y', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'Z', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'a', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'b', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'c', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'd', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'e', Eps), 13)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'f', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'g', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'h', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'i', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'j', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'k', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'l', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'm', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'n', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'o', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'p', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'q', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'r', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 's', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 't', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'u', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'v', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'w', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'x', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'y', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl 'z', Smbl 1), 4)
   transitions.Add(2, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 1), 65535)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl '\t', Smbl 4), 1)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl '\n', Smbl 4), 1)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl '\r', Smbl 4), 1)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl ' ', Smbl 4), 1)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl '(', Smbl 4), 7)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl ')', Smbl 4), 8)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl '*', Smbl 4), 11)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl '+', Smbl 4), 10)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl '-', Smbl 4), 3)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl '/', Smbl 4), 9)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl '0', Smbl 4), 2)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl '1', Smbl 4), 2)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl '2', Smbl 4), 2)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl '3', Smbl 4), 2)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl '4', Smbl 4), 2)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl '5', Smbl 4), 2)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl '6', Smbl 4), 2)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl '7', Smbl 4), 2)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl '8', Smbl 4), 2)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl '9', Smbl 4), 2)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl ';', Smbl 4), 6)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl '=', Smbl 4), 5)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'A', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'B', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'C', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'D', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'E', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'F', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'G', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'H', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'I', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'J', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'K', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'L', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'M', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'N', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'O', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'P', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'Q', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'R', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'S', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'T', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'U', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'V', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'W', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'X', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'Y', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'Z', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'a', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'b', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'c', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'd', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'e', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'f', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'g', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'h', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'i', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'j', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'k', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'l', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'm', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'n', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'o', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'p', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'q', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'r', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 's', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 't', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'u', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'v', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'w', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'x', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'y', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl 'z', Smbl 4), 4)
   transitions.Add(6, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 4), 65535)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl '\t', Smbl 3), 1)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl '\n', Smbl 3), 1)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl '\r', Smbl 3), 1)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl ' ', Smbl 3), 1)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl '(', Smbl 3), 7)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl ')', Smbl 3), 8)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl '*', Smbl 3), 11)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl '+', Smbl 3), 10)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl '-', Smbl 3), 3)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl '/', Smbl 3), 9)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl '0', Smbl 3), 2)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl '1', Smbl 3), 2)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl '2', Smbl 3), 2)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl '3', Smbl 3), 2)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl '4', Smbl 3), 2)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl '5', Smbl 3), 2)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl '6', Smbl 3), 2)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl '7', Smbl 3), 2)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl '8', Smbl 3), 2)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl '9', Smbl 3), 2)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl ';', Smbl 3), 6)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl '=', Smbl 3), 5)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'A', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'B', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'C', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'D', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'E', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'F', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'G', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'H', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'I', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'J', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'K', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'L', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'M', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'N', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'O', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'P', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'Q', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'R', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'S', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'T', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'U', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'V', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'W', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'X', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'Y', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'Z', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'a', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'b', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'c', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'd', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'e', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'f', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'g', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'h', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'i', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'j', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'k', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'l', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'm', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'n', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'o', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'p', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'q', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'r', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 's', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 't', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'u', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'v', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'w', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'x', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'y', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl 'z', Smbl 3), 4)
   transitions.Add(5, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 3), 65535)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl '\t', Smbl 2), 1)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl '\n', Smbl 2), 1)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl '\r', Smbl 2), 1)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl ' ', Smbl 2), 1)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl '(', Smbl 2), 7)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl ')', Smbl 2), 8)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl '*', Smbl 2), 11)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl '+', Smbl 2), 10)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl '-', Smbl 2), 3)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl '/', Smbl 2), 9)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl '0', Smbl 2), 2)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl '1', Smbl 2), 2)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl '2', Smbl 2), 2)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl '3', Smbl 2), 2)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl '4', Smbl 2), 2)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl '5', Smbl 2), 2)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl '6', Smbl 2), 2)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl '7', Smbl 2), 2)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl '8', Smbl 2), 2)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl '9', Smbl 2), 2)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl ';', Smbl 2), 6)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl '=', Smbl 2), 5)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'A', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'B', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'C', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'D', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'E', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'F', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'G', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'H', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'I', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'J', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'K', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'L', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'M', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'N', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'O', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'P', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'Q', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'R', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'S', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'T', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'U', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'V', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'W', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'X', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'Y', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'Z', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'a', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'b', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'c', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'd', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'e', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'f', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'g', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'h', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'i', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'j', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'k', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'l', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'm', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'n', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'o', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'p', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'q', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'r', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 's', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 't', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'u', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'v', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'w', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'x', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'y', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl 'z', Eps), 12)
   transitions.Add(4, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 2), 65535)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl '\t', Eps), 1)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl '\n', Eps), 1)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl '\r', Eps), 1)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl ' ', Eps), 1)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl '(', Eps), 7)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl ')', Eps), 8)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl '*', Eps), 11)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl '+', Eps), 10)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl '-', Eps), 3)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl '/', Eps), 9)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl '0', Eps), 16)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl '1', Eps), 16)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl '2', Eps), 16)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl '3', Eps), 16)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl '4', Eps), 16)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl '5', Eps), 16)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl '6', Eps), 16)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl '7', Eps), 16)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl '8', Eps), 16)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl '9', Eps), 16)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl ';', Eps), 6)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl '=', Eps), 5)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'A', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'B', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'C', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'D', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'E', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'F', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'G', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'H', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'I', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'J', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'K', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'L', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'M', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'N', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'O', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'P', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'Q', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'R', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'S', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'T', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'U', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'V', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'W', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'X', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'Y', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'Z', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'a', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'b', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'c', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'd', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'e', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'f', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'g', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'h', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'i', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'j', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'k', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'l', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'm', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'n', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'o', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'p', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'q', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'r', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 's', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 't', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'u', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'v', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'w', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'x', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'y', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl 'z', Eps), 4)
   transitions.Add(14, new EdgeLbl<_,_>(Smbl (char 65535), Eps), 65535)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl '\t', Smbl 1), 1)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl '\n', Smbl 1), 1)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl '\r', Smbl 1), 1)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl ' ', Smbl 1), 1)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl '(', Smbl 1), 7)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl ')', Smbl 1), 8)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl '*', Smbl 1), 11)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl '+', Smbl 1), 10)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl '-', Smbl 1), 3)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl '.', Eps), 14)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl '/', Smbl 1), 9)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl '0', Eps), 15)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl '1', Eps), 15)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl '2', Eps), 15)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl '3', Eps), 15)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl '4', Eps), 15)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl '5', Eps), 15)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl '6', Eps), 15)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl '7', Eps), 15)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl '8', Eps), 15)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl '9', Eps), 15)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl ';', Smbl 1), 6)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl '=', Smbl 1), 5)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'A', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'B', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'C', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'D', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'E', Eps), 13)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'F', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'G', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'H', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'I', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'J', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'K', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'L', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'M', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'N', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'O', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'P', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'Q', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'R', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'S', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'T', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'U', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'V', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'W', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'X', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'Y', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'Z', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'a', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'b', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'c', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'd', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'e', Eps), 13)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'f', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'g', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'h', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'i', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'j', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'k', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'l', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'm', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'n', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'o', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'p', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'q', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'r', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 's', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 't', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'u', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'v', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'w', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'x', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'y', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl 'z', Smbl 1), 4)
   transitions.Add(15, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 1), 65535)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl '\t', Eps), 1)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl '\n', Eps), 1)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl '\r', Eps), 1)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl ' ', Eps), 1)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl '(', Eps), 7)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl ')', Eps), 8)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl '*', Eps), 11)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl '+', Eps), 10)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl '-', Eps), 3)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl '/', Eps), 9)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl '0', Eps), 18)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl '1', Eps), 18)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl '2', Eps), 18)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl '3', Eps), 18)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl '4', Eps), 18)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl '5', Eps), 18)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl '6', Eps), 18)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl '7', Eps), 18)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl '8', Eps), 18)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl '9', Eps), 18)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl ';', Eps), 6)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl '=', Eps), 5)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'A', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'B', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'C', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'D', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'E', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'F', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'G', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'H', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'I', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'J', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'K', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'L', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'M', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'N', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'O', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'P', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'Q', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'R', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'S', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'T', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'U', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'V', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'W', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'X', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'Y', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'Z', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'a', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'b', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'c', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'd', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'e', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'f', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'g', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'h', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'i', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'j', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'k', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'l', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'm', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'n', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'o', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'p', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'q', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'r', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 's', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 't', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'u', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'v', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'w', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'x', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'y', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl 'z', Eps), 4)
   transitions.Add(13, new EdgeLbl<_,_>(Smbl (char 65535), Eps), 65535)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl '\t', Smbl 2), 1)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl '\n', Smbl 2), 1)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl '\r', Smbl 2), 1)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl ' ', Smbl 2), 1)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl '(', Smbl 2), 7)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl ')', Smbl 2), 8)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl '*', Smbl 2), 11)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl '+', Smbl 2), 10)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl '-', Smbl 2), 3)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl '/', Smbl 2), 9)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl '0', Smbl 2), 2)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl '1', Smbl 2), 2)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl '2', Smbl 2), 2)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl '3', Smbl 2), 2)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl '4', Smbl 2), 2)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl '5', Smbl 2), 2)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl '6', Smbl 2), 2)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl '7', Smbl 2), 2)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl '8', Smbl 2), 2)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl '9', Smbl 2), 2)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl ';', Smbl 2), 6)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl '=', Smbl 2), 5)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'A', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'B', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'C', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'D', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'E', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'F', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'G', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'H', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'I', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'J', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'K', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'L', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'M', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'N', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'O', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'P', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'Q', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'R', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'S', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'T', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'U', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'V', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'W', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'X', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'Y', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'Z', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'a', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'b', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'c', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'd', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'e', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'f', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'g', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'h', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'i', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'j', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'k', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'l', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'm', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'n', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'o', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'p', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'q', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'r', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 's', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 't', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'u', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'v', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'w', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'x', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'y', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl 'z', Eps), 12)
   transitions.Add(12, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 2), 65535)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl '\t', Smbl 1), 1)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl '\n', Smbl 1), 1)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl '\r', Smbl 1), 1)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl ' ', Smbl 1), 1)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl '(', Smbl 1), 7)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl ')', Smbl 1), 8)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl '*', Smbl 1), 11)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl '+', Smbl 1), 10)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl '-', Smbl 1), 3)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl '/', Smbl 1), 9)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl '0', Eps), 19)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl '1', Eps), 19)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl '2', Eps), 19)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl '3', Eps), 19)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl '4', Eps), 19)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl '5', Eps), 19)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl '6', Eps), 19)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl '7', Eps), 19)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl '8', Eps), 19)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl '9', Eps), 19)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl ';', Smbl 1), 6)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl '=', Smbl 1), 5)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'A', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'B', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'C', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'D', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'E', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'F', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'G', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'H', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'I', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'J', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'K', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'L', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'M', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'N', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'O', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'P', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'Q', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'R', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'S', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'T', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'U', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'V', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'W', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'X', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'Y', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'Z', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'a', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'b', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'c', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'd', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'e', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'f', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'g', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'h', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'i', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'j', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'k', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'l', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'm', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'n', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'o', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'p', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'q', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'r', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 's', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 't', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'u', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'v', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'w', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'x', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'y', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl 'z', Smbl 1), 4)
   transitions.Add(18, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 1), 65535)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl '\t', Smbl 1), 1)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl '\n', Smbl 1), 1)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl '\r', Smbl 1), 1)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl ' ', Smbl 1), 1)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl '(', Smbl 1), 7)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl ')', Smbl 1), 8)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl '*', Smbl 1), 11)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl '+', Smbl 1), 10)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl '-', Smbl 1), 3)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl '/', Smbl 1), 9)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl '0', Eps), 17)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl '1', Eps), 17)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl '2', Eps), 17)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl '3', Eps), 17)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl '4', Eps), 17)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl '5', Eps), 17)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl '6', Eps), 17)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl '7', Eps), 17)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl '8', Eps), 17)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl '9', Eps), 17)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl ';', Smbl 1), 6)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl '=', Smbl 1), 5)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'A', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'B', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'C', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'D', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'E', Eps), 13)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'F', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'G', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'H', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'I', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'J', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'K', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'L', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'M', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'N', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'O', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'P', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'Q', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'R', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'S', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'T', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'U', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'V', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'W', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'X', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'Y', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'Z', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'a', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'b', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'c', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'd', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'e', Eps), 13)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'f', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'g', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'h', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'i', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'j', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'k', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'l', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'm', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'n', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'o', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'p', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'q', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'r', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 's', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 't', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'u', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'v', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'w', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'x', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'y', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl 'z', Smbl 1), 4)
   transitions.Add(16, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 1), 65535)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl '\t', Smbl 1), 1)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl '\n', Smbl 1), 1)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl '\r', Smbl 1), 1)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl ' ', Smbl 1), 1)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl '(', Smbl 1), 7)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl ')', Smbl 1), 8)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl '*', Smbl 1), 11)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl '+', Smbl 1), 10)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl '-', Smbl 1), 3)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl '/', Smbl 1), 9)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl '0', Eps), 17)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl '1', Eps), 17)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl '2', Eps), 17)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl '3', Eps), 17)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl '4', Eps), 17)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl '5', Eps), 17)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl '6', Eps), 17)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl '7', Eps), 17)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl '8', Eps), 17)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl '9', Eps), 17)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl ';', Smbl 1), 6)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl '=', Smbl 1), 5)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'A', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'B', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'C', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'D', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'E', Eps), 13)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'F', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'G', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'H', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'I', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'J', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'K', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'L', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'M', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'N', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'O', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'P', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'Q', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'R', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'S', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'T', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'U', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'V', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'W', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'X', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'Y', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'Z', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'a', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'b', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'c', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'd', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'e', Eps), 13)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'f', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'g', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'h', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'i', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'j', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'k', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'l', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'm', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'n', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'o', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'p', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'q', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'r', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 's', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 't', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'u', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'v', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'w', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'x', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'y', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl 'z', Smbl 1), 4)
   transitions.Add(17, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 1), 65535)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl '\t', Smbl 1), 1)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl '\n', Smbl 1), 1)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl '\r', Smbl 1), 1)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl ' ', Smbl 1), 1)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl '(', Smbl 1), 7)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl ')', Smbl 1), 8)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl '*', Smbl 1), 11)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl '+', Smbl 1), 10)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl '-', Smbl 1), 3)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl '/', Smbl 1), 9)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl '0', Eps), 19)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl '1', Eps), 19)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl '2', Eps), 19)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl '3', Eps), 19)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl '4', Eps), 19)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl '5', Eps), 19)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl '6', Eps), 19)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl '7', Eps), 19)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl '8', Eps), 19)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl '9', Eps), 19)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl ';', Smbl 1), 6)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl '=', Smbl 1), 5)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'A', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'B', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'C', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'D', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'E', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'F', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'G', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'H', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'I', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'J', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'K', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'L', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'M', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'N', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'O', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'P', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'Q', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'R', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'S', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'T', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'U', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'V', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'W', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'X', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'Y', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'Z', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'a', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'b', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'c', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'd', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'e', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'f', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'g', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'h', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'i', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'j', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'k', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'l', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'm', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'n', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'o', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'p', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'q', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'r', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 's', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 't', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'u', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'v', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'w', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'x', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'y', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl 'z', Smbl 1), 4)
   transitions.Add(19, new EdgeLbl<_,_>(Smbl (char 65535), Smbl 1), 65535)
   new FST<_,_>(startState, finishState, transitions)

let actions () =
   [|

      (fun (gr : GraphTokenValue<_>) ->
                              None );
      (fun (gr : GraphTokenValue<_>) ->
                                                                  NUMBER(gr) |> Some );
      (fun (gr : GraphTokenValue<_>) ->
                           VARIABLE(gr) |> Some );
      (fun (gr : GraphTokenValue<_>) ->
                       EQ(gr) |> Some );
      (fun (gr : GraphTokenValue<_>) ->
                       SEMI(gr) |> Some );
      (fun (gr : GraphTokenValue<_>) ->
                       MINUS(gr) |> Some );
      (fun (gr : GraphTokenValue<_>) ->
                       LBRACE(gr) |> Some );
      (fun (gr : GraphTokenValue<_>) ->
                       RBRACE(gr) |> Some );
      (fun (gr : GraphTokenValue<_>) ->
                       DIV(gr) |> Some );
      (fun (gr : GraphTokenValue<_>) ->
                       PLUS(gr) |> Some );
      (fun (gr : GraphTokenValue<_>) ->
                       MUL(gr) |> Some );

   |]


let alphabet () = 
 new HashSet<_>([| Smbl (char 65535); Smbl '\t'; Smbl '\n'; Smbl '\r'; Smbl ' '; Smbl '('; Smbl ')'; Smbl '*'; Smbl '+'; Smbl '-'; Smbl '/'; Smbl '0'; Smbl '1'; Smbl '2'; Smbl '3'; Smbl '4'; Smbl '5'; Smbl '6'; Smbl '7'; Smbl '8'; Smbl '9'; Smbl ';'; Smbl '='; Smbl 'A'; Smbl 'B'; Smbl 'C'; Smbl 'D'; Smbl 'E'; Smbl 'F'; Smbl 'G'; Smbl 'H'; Smbl 'I'; Smbl 'J'; Smbl 'K'; Smbl 'L'; Smbl 'M'; Smbl 'N'; Smbl 'O'; Smbl 'P'; Smbl 'Q'; Smbl 'R'; Smbl 'S'; Smbl 'T'; Smbl 'U'; Smbl 'V'; Smbl 'W'; Smbl 'X'; Smbl 'Y'; Smbl 'Z'; Smbl 'a'; Smbl 'b'; Smbl 'c'; Smbl 'd'; Smbl 'e'; Smbl 'f'; Smbl 'g'; Smbl 'h'; Smbl 'i'; Smbl 'j'; Smbl 'k'; Smbl 'l'; Smbl 'm'; Smbl 'n'; Smbl 'o'; Smbl 'p'; Smbl 'q'; Smbl 'r'; Smbl 's'; Smbl 't'; Smbl 'u'; Smbl 'v'; Smbl 'w'; Smbl 'x'; Smbl 'y'; Smbl 'z'; Smbl '.';|])

let tokenize eof approximation = Tokenize (fstLexer()) (actions()) (alphabet()) eof approximation
