//this tyables was generated by RACC
//source grammar:..\..\..\..\Tests\test0002.yrd
//date:11/13/2010 14:11:17

#light "off"
module Yard.Generators._RACCGenerator.Tables

open Yard.Generators._RACCGenerator

let autumataDict = 
dict [|("s",{ 
   DIDToStateMap = dict [|(0,(State 0));(1,(State 1));(2,DummyState)|];
   DStartState   = 0;
   DFinaleStates = Set.ofArray [|1|];
   DRules        = Set.ofArray [|{ 
   FromStateID = 0;
   Symbol      = (DSymbol "e");
   Label       = Set.ofArray [|List.ofArray [|(FATrace TSeqS);(FATrace TSmbS)|];List.ofArray [|(FATrace TSmbS)|]|];
   ToStateID   = 1;
}
;{ 
   FromStateID = 1;
   Symbol      = Dummy;
   Label       = Set.ofArray [|List.ofArray [|(FATrace TSmbE);(FATrace TSeqE)|]|];
   ToStateID   = 2;
}
|];
}
);("e",{ 
   DIDToStateMap = dict [|(0,(State 0));(1,(State 1));(2,(State 2));(3,(State 3));(4,(State 4));(5,(State 5));(6,(State 6));(7,(State 7));(8,(State 8));(9,(State 9));(10,(State 10));(11,DummyState);(12,DummyState);(13,DummyState);(14,DummyState);(15,DummyState)|];
   DStartState   = 0;
   DFinaleStates = Set.ofArray [|1;10;4;6;8|];
   DRules        = Set.ofArray [|{ 
   FromStateID = 0;
   Symbol      = (DSymbol "NUMBER");
   Label       = Set.ofArray [|List.ofArray [|(FATrace TAlt1S);(FATrace TSeqS);(FATrace TSeqS);(FATrace TSmbS)|];List.ofArray [|(FATrace TAlt1S);(FATrace TSeqS);(FATrace TSmbS)|];List.ofArray [|(FATrace TAlt2S);(FATrace TAlt1S);(FATrace TSeqS);(FATrace TSeqS);(FATrace TSmbS)|];List.ofArray [|(FATrace TAlt2S);(FATrace TAlt2S);(FATrace TAlt1S);(FATrace TSeqS);(FATrace TSeqS);(FATrace TSmbS)|];List.ofArray [|(FATrace TAlt2S);(FATrace TAlt2S);(FATrace TAlt2S);(FATrace TAlt1S);(FATrace TSeqS);(FATrace TSeqS);(FATrace TSmbS)|];List.ofArray [|(FATrace TAlt2S);(FATrace TAlt2S);(FATrace TAlt2S);(FATrace TAlt2S);(FATrace TSeqS);(FATrace TSeqS);(FATrace TSmbS)|];List.ofArray [|(FATrace TAlt2S);(FATrace TAlt2S);(FATrace TAlt2S);(FATrace TSeqS);(FATrace TSeqS);(FATrace TSmbS)|];List.ofArray [|(FATrace TAlt2S);(FATrace TAlt2S);(FATrace TSeqS);(FATrace TSeqS);(FATrace TSmbS)|];List.ofArray [|(FATrace TAlt2S);(FATrace TSeqS);(FATrace TSeqS);(FATrace TSmbS)|];List.ofArray [|(FATrace TSeqS);(FATrace TSeqS);(FATrace TSmbS)|];List.ofArray [|(FATrace TSeqS);(FATrace TSmbS)|];List.ofArray [|(FATrace TSmbS)|]|];
   ToStateID   = 1;
}
;{ 
   FromStateID = 0;
   Symbol      = (DSymbol "e");
   Label       = Set.ofArray [|List.ofArray [|(FATrace TAlt1S);(FATrace TSeqS);(FATrace TSeqS);(FATrace TSmbS)|];List.ofArray [|(FATrace TAlt1S);(FATrace TSeqS);(FATrace TSmbS)|];List.ofArray [|(FATrace TAlt2S);(FATrace TAlt1S);(FATrace TSeqS);(FATrace TSeqS);(FATrace TSmbS)|];List.ofArray [|(FATrace TAlt2S);(FATrace TAlt2S);(FATrace TAlt1S);(FATrace TSeqS);(FATrace TSeqS);(FATrace TSmbS)|];List.ofArray [|(FATrace TAlt2S);(FATrace TAlt2S);(FATrace TAlt2S);(FATrace TAlt1S);(FATrace TSeqS);(FATrace TSeqS);(FATrace TSmbS)|];List.ofArray [|(FATrace TAlt2S);(FATrace TAlt2S);(FATrace TAlt2S);(FATrace TAlt2S);(FATrace TSeqS);(FATrace TSeqS);(FATrace TSmbS)|];List.ofArray [|(FATrace TAlt2S);(FATrace TAlt2S);(FATrace TAlt2S);(FATrace TSeqS);(FATrace TSeqS);(FATrace TSmbS)|];List.ofArray [|(FATrace TAlt2S);(FATrace TAlt2S);(FATrace TSeqS);(FATrace TSeqS);(FATrace TSmbS)|];List.ofArray [|(FATrace TAlt2S);(FATrace TSeqS);(FATrace TSeqS);(FATrace TSmbS)|];List.ofArray [|(FATrace TSeqS);(FATrace TSeqS);(FATrace TSmbS)|];List.ofArray [|(FATrace TSeqS);(FATrace TSmbS)|];List.ofArray [|(FATrace TSmbS)|]|];
   ToStateID   = 2;
}
;{ 
   FromStateID = 10;
   Symbol      = Dummy;
   Label       = Set.ofArray [|List.ofArray [|(FATrace TSmbE);(FATrace TSeqE);(FATrace TAlt1E)|];List.ofArray [|(FATrace TSmbE);(FATrace TSeqE);(FATrace TSeqE);(FATrace TAlt1E);(FATrace TAlt2E);(FATrace TAlt2E);(FATrace TAlt2E)|];List.ofArray [|(FATrace TSmbE);(FATrace TSeqE);(FATrace TSeqE);(FATrace TAlt1E);(FATrace TAlt2E);(FATrace TAlt2E)|];List.ofArray [|(FATrace TSmbE);(FATrace TSeqE);(FATrace TSeqE);(FATrace TAlt1E);(FATrace TAlt2E)|];List.ofArray [|(FATrace TSmbE);(FATrace TSeqE);(FATrace TSeqE);(FATrace TAlt2E);(FATrace TAlt2E);(FATrace TAlt2E);(FATrace TAlt2E)|]|];
   ToStateID   = 15;
}
;{ 
   FromStateID = 1;
   Symbol      = Dummy;
   Label       = Set.ofArray [|List.ofArray [|(FATrace TSmbE);(FATrace TSeqE);(FATrace TAlt1E)|];List.ofArray [|(FATrace TSmbE);(FATrace TSeqE);(FATrace TSeqE);(FATrace TAlt1E);(FATrace TAlt2E);(FATrace TAlt2E);(FATrace TAlt2E)|];List.ofArray [|(FATrace TSmbE);(FATrace TSeqE);(FATrace TSeqE);(FATrace TAlt1E);(FATrace TAlt2E);(FATrace TAlt2E)|];List.ofArray [|(FATrace TSmbE);(FATrace TSeqE);(FATrace TSeqE);(FATrace TAlt1E);(FATrace TAlt2E)|];List.ofArray [|(FATrace TSmbE);(FATrace TSeqE);(FATrace TSeqE);(FATrace TAlt2E);(FATrace TAlt2E);(FATrace TAlt2E);(FATrace TAlt2E)|]|];
   ToStateID   = 11;
}
;{ 
   FromStateID = 2;
   Symbol      = (DSymbol "DIV");
   Label       = Set.ofArray [|List.ofArray [|(FATrace TSmbE);(FATrace TSmbS)|]|];
   ToStateID   = 9;
}
;{ 
   FromStateID = 2;
   Symbol      = (DSymbol "MINUS");
   Label       = Set.ofArray [|List.ofArray [|(FATrace TSmbE);(FATrace TSmbS)|]|];
   ToStateID   = 5;
}
;{ 
   FromStateID = 2;
   Symbol      = (DSymbol "MULT");
   Label       = Set.ofArray [|List.ofArray [|(FATrace TSmbE);(FATrace TSmbS)|]|];
   ToStateID   = 7;
}
;{ 
   FromStateID = 2;
   Symbol      = (DSymbol "PLUS");
   Label       = Set.ofArray [|List.ofArray [|(FATrace TSmbE);(FATrace TSmbS)|]|];
   ToStateID   = 3;
}
;{ 
   FromStateID = 3;
   Symbol      = (DSymbol "e");
   Label       = Set.ofArray [|List.ofArray [|(FATrace TSmbE);(FATrace TSmbS)|]|];
   ToStateID   = 4;
}
;{ 
   FromStateID = 4;
   Symbol      = Dummy;
   Label       = Set.ofArray [|List.ofArray [|(FATrace TSmbE);(FATrace TSeqE);(FATrace TAlt1E)|];List.ofArray [|(FATrace TSmbE);(FATrace TSeqE);(FATrace TSeqE);(FATrace TAlt1E);(FATrace TAlt2E);(FATrace TAlt2E);(FATrace TAlt2E)|];List.ofArray [|(FATrace TSmbE);(FATrace TSeqE);(FATrace TSeqE);(FATrace TAlt1E);(FATrace TAlt2E);(FATrace TAlt2E)|];List.ofArray [|(FATrace TSmbE);(FATrace TSeqE);(FATrace TSeqE);(FATrace TAlt1E);(FATrace TAlt2E)|];List.ofArray [|(FATrace TSmbE);(FATrace TSeqE);(FATrace TSeqE);(FATrace TAlt2E);(FATrace TAlt2E);(FATrace TAlt2E);(FATrace TAlt2E)|]|];
   ToStateID   = 12;
}
;{ 
   FromStateID = 5;
   Symbol      = (DSymbol "e");
   Label       = Set.ofArray [|List.ofArray [|(FATrace TSmbE);(FATrace TSmbS)|]|];
   ToStateID   = 6;
}
;{ 
   FromStateID = 6;
   Symbol      = Dummy;
   Label       = Set.ofArray [|List.ofArray [|(FATrace TSmbE);(FATrace TSeqE);(FATrace TAlt1E)|];List.ofArray [|(FATrace TSmbE);(FATrace TSeqE);(FATrace TSeqE);(FATrace TAlt1E);(FATrace TAlt2E);(FATrace TAlt2E);(FATrace TAlt2E)|];List.ofArray [|(FATrace TSmbE);(FATrace TSeqE);(FATrace TSeqE);(FATrace TAlt1E);(FATrace TAlt2E);(FATrace TAlt2E)|];List.ofArray [|(FATrace TSmbE);(FATrace TSeqE);(FATrace TSeqE);(FATrace TAlt1E);(FATrace TAlt2E)|];List.ofArray [|(FATrace TSmbE);(FATrace TSeqE);(FATrace TSeqE);(FATrace TAlt2E);(FATrace TAlt2E);(FATrace TAlt2E);(FATrace TAlt2E)|]|];
   ToStateID   = 13;
}
;{ 
   FromStateID = 7;
   Symbol      = (DSymbol "e");
   Label       = Set.ofArray [|List.ofArray [|(FATrace TSmbE);(FATrace TSmbS)|]|];
   ToStateID   = 8;
}
;{ 
   FromStateID = 8;
   Symbol      = Dummy;
   Label       = Set.ofArray [|List.ofArray [|(FATrace TSmbE);(FATrace TSeqE);(FATrace TAlt1E)|];List.ofArray [|(FATrace TSmbE);(FATrace TSeqE);(FATrace TSeqE);(FATrace TAlt1E);(FATrace TAlt2E);(FATrace TAlt2E);(FATrace TAlt2E)|];List.ofArray [|(FATrace TSmbE);(FATrace TSeqE);(FATrace TSeqE);(FATrace TAlt1E);(FATrace TAlt2E);(FATrace TAlt2E)|];List.ofArray [|(FATrace TSmbE);(FATrace TSeqE);(FATrace TSeqE);(FATrace TAlt1E);(FATrace TAlt2E)|];List.ofArray [|(FATrace TSmbE);(FATrace TSeqE);(FATrace TSeqE);(FATrace TAlt2E);(FATrace TAlt2E);(FATrace TAlt2E);(FATrace TAlt2E)|]|];
   ToStateID   = 14;
}
;{ 
   FromStateID = 9;
   Symbol      = (DSymbol "e");
   Label       = Set.ofArray [|List.ofArray [|(FATrace TSmbE);(FATrace TSmbS)|]|];
   ToStateID   = 10;
}
|];
}
)|]

let items = 
List.ofArray [|("s",0);("s",1);("s",2);("e",0);("e",1);("e",2);("e",3);("e",4);("e",5);("e",6);("e",7);("e",8);("e",9);("e",10);("e",11);("e",12);("e",13);("e",14);("e",15)|]

let gotoSet = 
Set.ofArray [|(-1144281312,("e",5));(123052070,("e",10));(123052070,("e",2));(123052815,("e",2));(123052908,("e",2));(123052908,("e",4));(123052970,("e",2));(123052970,("e",6));(123053032,("e",2));(123053032,("e",8));(123072121,("e",2));(123072121,("s",1));(1302675592,("e",9));(1800900912,("e",15));(1800900978,("e",14));(1800901211,("e",11));(1800901308,("e",13));(1800901374,("e",12));(1800920813,("s",2));(1904094491,("e",1));(1904094553,("e",1));(1904094654,("e",1));(1904094685,("e",1));(1904094871,("e",1));(1904107720,("e",1));(452906003,("e",3));(864558179,("e",7))|]

