//this tyables was generated by RACC
//source grammar:..\..\..\..\Tests\test002.yrd
//date:9/17/2010 15:56:14

#light "off"
module Yard.Generators._RACCGenerator.Tables

open Yard.Generators._RACCGenerator

let autumataDict = 
dict [|("s",{ 
   DIDToStateMap = dict [|(0,(State 0));(1,(State 1));(2,DummyState)|];
   DStartState   = 0;
   DFinaleStates = set [1];
   DRules        = Set.ofArray [|{ 
   FromStateID = 0;
   Symbol      = (DSymbol "expr");
   Label       = set [[(FATrace TSmbS)]; [(FATrace TSeqS); (FATrace TSmbS)]];
   ToStateID   = 1;
}
;{ 
   FromStateID = 1;
   Symbol      = Dummy;
   Label       = set [[(FATrace TSmbE); (FATrace TSeqE)]];
   ToStateID   = 2;
}
|];
}
);("expr",{ 
   DIDToStateMap = dict [|(0,(State 0));(1,(State 1));(2,(State 2));(3,(State 3));(4,DummyState)|];
   DStartState   = 0;
   DFinaleStates = set [3];
   DRules        = Set.ofArray [|{ 
   FromStateID = 0;
   Symbol      = (DSymbol "NUMBER");
   Label       = set [[(FATrace TSmbS)]; [(FATrace TSeqS); (FATrace TSmbS)]];
   ToStateID   = 1;
}
;{ 
   FromStateID = 1;
   Symbol      = (DSymbol "PLUS");
   Label       = set [[(FATrace TSmbE); (FATrace TSmbS)]];
   ToStateID   = 2;
}
;{ 
   FromStateID = 2;
   Symbol      = (DSymbol "NUMBER");
   Label       = set [[(FATrace TSmbE); (FATrace TSmbS)]];
   ToStateID   = 3;
}
;{ 
   FromStateID = 3;
   Symbol      = Dummy;
   Label       = set [[(FATrace TSmbE); (FATrace TSeqE)]];
   ToStateID   = 4;
}
|];
}
)|]

let items = 
List.ofArray [|("s",0);("s",1);("s",2);("expr",0);("expr",1);("expr",2);("expr",3);("expr",4)|]

let gotoSet = 
Set.ofArray [|(-1374947426,("expr",2));(-542987785,("expr",4));(-748915389,("s",1));(-980740592,("expr",1));(-980740654,("expr",3));(1800920813,("s",2))|]

