module LexerHelper

open Microsoft.FSharp.Text.Lexing
open Microsoft.FSharp.Text
open Microsoft.FSharp.Reflection
open Yard.Examples.MSParser
open Yard.Utils.SourceText
open Yard.Utils.StructClass

open System

type Collections.Generic.IDictionary<'k,'v> with
    member d.TryGetValue' k = 
        let mutable res = Unchecked.defaultof<'v> 
        let exist = d.TryGetValue(k, &res)
        if exist then Some res else None
    member d.Add'(k,v) =
        if not (d.ContainsKey k) then d.Add(k,v);true else false

exception IdentToken

let getKwToken = 
    let nameToUnionCtor (uci:UnionCaseInfo) = (uci.Name, FSharpValue.PreComputeUnionConstructor(uci))
    let ucis = FSharpType.GetUnionCases (typeof<Token>) |> Array.map nameToUnionCtor  |> dict 
    fun (name:string) defaultSourceText ->
        let upperName = "KW_" + name.ToUpperInvariant()
        ucis.TryGetValue' upperName
        |> Option.map (fun ctor ->  ctor [| defaultSourceText |] :?>Token)

let lexeme lexbuf = LexBuffer<_>.LexemeString lexbuf

//function

let commendepth = ref 0
let startPos = ref Position.Empty
let str_buf = new System.Text.StringBuilder()

let appendBuf (str:string) = str_buf.Append(str) |> ignore
let clearBuf () = str_buf.Clear() |> ignore
  
let makeIdent notKeyWord (name:string) (startPos, endPos) =
  let prefix = 
    if String.length name >= 2 
    then name.[0..1] 
    else ""
  let defaultSourceText =  
    new SourceText(name, SourceRange.ofTuple (startPos,endPos))
  if prefix = "@@" then GLOBALVAR(defaultSourceText)
  //else if prefix = "##" then GLOBALTEMPOBJ(name)
  else if name.[0] = '@' then LOCALVAR(defaultSourceText)
  //else if name.[0] = '#' then TEMPOBJ(name)
  else if prefix = "%%" then STOREDPROCEDURE(defaultSourceText)
  else if notKeyWord then IDENT(defaultSourceText)
  else  match getKwToken name defaultSourceText with
        | Some(kwToken) -> kwToken
        | None -> IDENT(defaultSourceText)


let defaultSourceText id (lexbuf : LexBuffer<_>) value =
    new SourceText(value
        , SourceRange.ofTuple(new Pair (id,int64 lexbuf.StartPos.AbsoluteOffset * _symbolL)
                               , new Pair(id, int64 lexbuf.EndPos.AbsoluteOffset * _symbolL)))

let tokenPos token =
    match token with
    | KW_PRINT(x)
    | KW_FOREIGN(x)
    | KW_NO(x)
    | KW_WHILE(x)
    | KW_DATETIME(x)
    | KW_DROP(x)
    | KW_ABSOLUTE(x)
    | KW_FETCH(x)
    | KW_FETCH(x)
    | KW_FIRST(x)
    | KW_GLOBAL(x)
    | KW_IS_MEMBER(x)
    | KW_LAST(x)
    | KW_LOCAL(x)
    | KW_NEXT(x)
    | KW_PRIOR(x)
    | KW_RELATIVE(x)
    | KW_ROLLBACK(x)
    | KW_COMMIT (x)
    | KW_MARK (x)
    | KW_TRAN (x)    
    | KW_TRANSACTION (x)    
    | COMMA (x)
    | DEC_NUMBER (x)
    | DOT (x)
    | DOUBLE_COLON (x)
    | EMPTY (x)
    | EOF (x)
    | GLOBALVAR (x)
    | IDENT (x)
    | KW_ABSENT (x)
    | KW_ACTION (x)
    | KW_ALL (x)
    | KW_ALLOW_PAGE_LOCKS (x)
    | KW_ALLOW_ROW_LOCKS (x)
    | KW_AND (x)
    | KW_ANSI_DEFAULTS (x)
    | KW_ANSI_NULLS (x)
    | KW_ANSI_NULL_DFLT (x)
    | KW_ANSI_PADDING (x)
    | KW_ANSI_WARNINGS (x)
    | KW_ANY (x)
    | KW_AS (x)
    | KW_ASC (x)
    | KW_AT (x)
    | KW_AUTO (x)
    | KW_AVG (x)
    | KW_BASE64 (x)
    | KW_BEGIN (x)
    | KW_BETWEEN (x)
    | KW_BIGINT (x)
    | KW_BINARY (x)
    | KW_BIT (x)
    | KW_BROWSE (x)
    | KW_BULK (x)
    | KW_BY (x)
    | KW_CALLER (x)
    | KW_CASCADE (x)
    | KW_CASE (x)
    | KW_CHAR (x)
    | KW_CHECK (x)
    | KW_CLASS (x)
    | KW_CLUSTERED (x)
    | KW_CODEPAGE (x)
    | KW_COLLATE (x)
    | KW_COMPUTE (x)
    | KW_CONCAT (x)
    | KW_CONCAT_NULL_YIELDS_NULL (x)
    | KW_CONSTRAINT (x)
    | KW_CONTAINSTABLE (x)
    //| KW_CONTENT (x)
    | KW_COUNT (x)
    | KW_CREATE (x)
    | KW_CROSS (x)
    | KW_CUBE (x)
    | KW_CURSOR (x)
    | KW_CURSOR_CLOSE_ON_COMMIT (x)
    | KW_DECIMAL (x)
    | KW_DECLARE (x)
    | KW_DEFAULT (x)
    | KW_DELETE (x)
    | KW_DELETED (x)
    | KW_DENSE_RANK (x)
    | KW_DESC (x)
    | KW_DISTINCT (x)
   // | KW_DOCUMENT (x)
    | KW_DYNAMIC (x)
    | KW_EAD (x)
    | KW_ELEMENTS (x)
    | KW_ELSE (x)
    | KW_ENCRYPTION (x)
    | KW_END (x)
    | KW_ERRORFILE (x)
    | KW_ESCAPE (x)
    | KW_EXCEPT (x)
    | KW_EXEC (x)
    | KW_EXECUTE (x)
    | KW_EXECUTE_AS_Clause (x)
    | KW_EXISTS (x)
    | KW_EXPAND (x)
    | KW_EXPLICIT (x)
    | KW_FAST (x)
    | KW_FASTFIRSTROW (x)
    | KW_FAST_FORWARD (x)
    | KW_FILLFACTOR (x)
    | KW_FIRSTROW (x)
    | KW_FLOAT (x)
    | KW_FMTONLY (x)
    | KW_FOR (x)
    | KW_FORCE (x)
    | KW_FORCED (x)
    | KW_FORCEPLAN (x)
    | KW_FORMATFILE (x)
    | KW_FORMSOF (x)
    | KW_FORWARD_ONLY (x)
    | KW_FREETEXTTABLE (x)
    | KW_FROM (x)
    | KW_FULL (x)
    | KW_GO (x)
    | KW_GROUP (x)
    | KW_HASH (x)
    | KW_HAVING (x)
    | KW_HOLDLOCK (x)
    | KW_IDENTITY (x)
    | KW_IF (x)
    | KW_IGNORE_CONSTRAINTS (x)
    | KW_IGNORE_DUP_KEY (x)
    | KW_IGNORE_TRIGGERS (x)
    | KW_IMPLICIT_TRANSACTIONS (x)
    | KW_IN (x)
    | KW_INDEX (x)
    | KW_INFLECTIONAL (x)
    | KW_INNER (x)
    | KW_INSERT (x)
    | KW_INSERTED (x)
    | KW_INT (x)
    | KW_INTERSECT (x)
    | KW_INTO (x)
    | KW_IO (x)
    | KW_IS (x)
    | KW_ISABOUT (x)
    | KW_JOIN (x)
    | KW_KEEP (x)
    | KW_KEEPDEFAULTS (x)
    | KW_KEEPFIXED (x)
    | KW_KEEPIDENTITY (x)
    | KW_KEY (x)
    | KW_KEYSET (x)
    | KW_LANGUAGE (x)
    | KW_LASTROW (x)
    | KW_LEFT (x)
    | KW_LIKE (x)
    | KW_LOG (x)
    | KW_LOGIN (x)
    | KW_LOOP (x)
    | KW_LOWER (x)
    | KW_MAX (x)
    | KW_MAXDOP (x)
    | KW_MAXERRORS (x)
    | KW_MAXRECURSION (x)
    | KW_MDW_CONTROL (x)
    | KW_MERGE (x)
    | KW_MIN (x)
    | KW_MONEY (x)
    | KW_NCHAR (x)
    | KW_NEAR (x)
    | KW_NOCOUNT (x)
    | KW_NOEXEC (x)
    | KW_NOEXPAND (x)
    | KW_NOLOCK (x)
    | KW_NONCLUSTERED (x)
    | KW_NOT (x)
    | KW_NOWAIT (x)
    | KW_NTILE (x)
    | KW_NULL (x)
    | KW_NUMERIC (x)
    | KW_NUMERIC_ROUNDABORT (x)
    | KW_NVARCHAR (x)
    | KW_OF (x)
    | KW_OFF (x)
    | KW_ON (x)
    | KW_OPENDATASOURCE (x)
    | KW_OPENQUERY (x)
    | KW_OPENROWSET (x)
    | KW_OPTIMISTIC (x)
    | KW_OPTIMIZE (x)
    | KW_OPTION (x)
    | KW_OR (x)
    | KW_ORDER (x)
    | KW_OUT (x)
    | KW_OUTER (x)
    | KW_OUTPUT (x)
    | KW_OVER (x)
    | KW_OWNER (x)
    | KW_PAD_INDEX (x)
    | KW_PAGLOCK (x)
    | KW_PARAMETERIZATION (x)
    | KW_PARSEONLY (x)
    | KW_PARTITION (x)
    | KW_PATH (x)
    | KW_PERCENT (x)
    | KW_PERSISTED (x)
    | KW_PIVOT (x)
    | KW_PLAN (x)
    | KW_PRIMARY (x)
    | KW_PROC (x)
    | KW_PROCEDURE (x)
    | KW_PROFILE (x)
    | KW_QUOTED_IDENTIFIER (x)
    | KW_RAISERROR (x)
    | KW_RANK (x)
    | KW_RAW (x)
    | KW_READCOMMITTED (x)
    | KW_READCOMMITTEDLOCK (x)
    | KW_READONLY (x)
    | KW_READPAST (x)
    | KW_READUNCOMMITTED (x)
    | KW_READ_ONLY (x)
    | KW_REAL (x)
    | KW_RECOMPILE (x)
    | KW_REFERENCES (x)
    | KW_REMOTE (x)
    | KW_REMOTE_PROC_TRANSACTIONS (x)
    | KW_REPEATABLE (x)
    | KW_REPEATABLEREAD (x)
    | KW_REPLICATION (x)
    | KW_RETURN (x)
    | KW_RIGHT (x)
    | KW_ROBUST (x)
    | KW_ROLLBACK (x)
    | KW_ROLLUP (x)
    | KW_ROOT (x)
    | KW_ROWGUID (x)
    | KW_ROWGUIDCOL (x)
    | KW_ROWLOCK (x)
    | KW_ROWS (x)
    | KW_ROWS_PER_BATCH (x)
    | KW_ROW_NUMBER (x)
    | KW_SCALAR_DATA_TYPE (x)
    | KW_SCROLL (x)
    | KW_SCROLL_LOCKS (x)
    | KW_SELECT (x)
    | KW_SELF (x)
    | KW_SERIALIZABLE (x)
    | KW_SET (x)
    | KW_SETERROR (x)
    | KW_SHOWPLAN_ALL (x)
    | KW_SHOWPLAN_TEXT (x)
    | KW_SHOWPLAN_XML (x)
    | KW_SIMPLE (x)
    | KW_SINGLE_BLOB (x)
    | KW_SINGLE_CLOB (x)
    | KW_SINGLE_NCLOB (x)
    | KW_SMALLINT (x)
    | KW_SMALLMONEY (x)
    | KW_SOME (x)
    | KW_SQL_VARIANT (x)
    | KW_STATE (x)
    | KW_STATIC (x)
    | KW_STATISTICS (x)
    | KW_STATISTICS_NORECOMPUTE (x)
    | KW_SUM (x)
    | KW_SYSNAME (x)
    | KW_SYSTEM (x)
    | KW_TABLE (x)
    | KW_TABLESAMPLE (x)
    | KW_TABLOCK (x)
    | KW_TABLOCKX (x)
    | KW_THEN (x)
    | KW_THESAURUS (x)
    | KW_TEXTIMAGE_ON (x)
    | KW_TIES (x)
    | KW_TIME (x)
    | KW_TINYINT (x)
    | KW_TOP (x)
    | KW_TYPE (x)
    | KW_TYPE_WARNING (x)
    | KW_UNION (x)
    | KW_UNIQUE (x)
    | KW_UNPIVOT (x)
    | KW_UPDATE (x)
    | KW_UPDLOCK (x)
    | KW_USE (x)
    | KW_USER (x)
    | KW_VALUES (x)
    | KW_VARBINARY (x)
    | KW_VARCHAR (x)
    | KW_VARYING (x)
    | KW_VIEWS (x)
    | KW_WHEN (x)
    | KW_WHERE (x)
    | KW_WITH (x)
    | KW_XACT_ABORT (x)
    | KW_XLOCK (x)
    | KW_XML (x)
    | KW_XMLDATA (x)
    | KW_XMLSCHEMA (x)
    | KW_XSINIL (x)
    | LBRACKET (x)
    | LOCALVAR (x)
    | LPAREN (x)
    | ONLY (x)
    | OP_AND_EQ (x)
    | OP_DIV (x)
    | OP_DIV_EQ (x)
    | OP_EQ (x)
    | OP_GT (x)
    | OP_LT (x)
    | OP_MINUS (x)
    | OP_MINUS_EQ (x)
    | OP_MOD (x)
    | OP_MOD_EQ (x)
    | OP_MT (x)
    | OP_MUL_EQ (x)
    | OP_OR_EQ (x)
    | OP_PLUS (x)
    | OP_PLUS_EQ (x)
    | OP_TILDA (x)
    | OP_XOR_EQ (x)
    | PLUS (x)
    | RBRACKET (x)
    | RPAREN (x)
    | SEMI (x)
    | STAR (x)
    | STOREDPROCEDURE (x)
    | STRING_CONST (x)
    | WEIGHT (x) -> x.Range.Start, x.Range.End