//this tables was generated by GNESCC
//source grammar:D:\YC\recursive-ascent\Tests\GNESCC\test_seq\test_seq.yrd
//date:10/8/2011 6:41:52 PM

module Yard.Generators.GNESCCGenerator.Tables_seq

open Yard.Generators.GNESCCGenerator
open Yard.Generators.GNESCCGenerator.CommonTypes

type symbol =
    | T_MINUS
    | T_LBR
    | NT_start
    | T_MULT
    | T_PLUS
    | T_NUMBER
    | NT_e
    | NT_s
    | NT_gnesccStart
let getTag smb =
    match smb with
    | T_RBR -> 6
    | T_MULT -> 8
    | NT_start -> 4
    | NT_gnesccStart -> 2
let getName tag =
    match tag with
    | 6 -> T_RBR
    | 8 -> T_MULT
    | 4 -> NT_start
    | 7 -> T_PLUS
    | 6 -> T_NUMBER
    | 5 -> NT_e
    | 4 -> NT_s
    | 2 -> NT_gnesccStart
    | _ -> failwith "getName: bad tag."
let prodToNTerm = 
  [| 1; 0 |];
let symbolIdx = 
  [| 2; 3; 1; 3; 0; 1; 0 |];
let startKernelIdxs =  [0]
let isStart =
  [| [| true; true |];
     [| false; false |];
     [| false; true |];
     [| false; false |];
     [| false; false; false |];
     [| false; false; true |];
     [| false; false; true |];
     [| false; false; true |]; |]
let gotoTable =
  [| [| Some 1; None |];
     [| None; None |];
     [| Some 3; None |];
     [| None; None |];
     [| None; None; None |];
     [| Some 3; None; None |];
     [| Some 3; None; None |];
     [| Some 3; None; None |]; |]
let actionTable = 
  [| [| [Error]; [Error]; [Error]; [Shift 4]; [Error]; [Error] |];
     [| [Accept]; [Accept]; [Accept]; [Accept] |];
     [| [Shift 7]; [Shift 6]; [Shift 5]; [Error]; [Error]; [Reduce 1] |];
     [| [Shift 7]; [Shift 6]; [Shift 5]; [Reduce 2]; [Error]; [Reduce 2] |];
     [| [Error]; [Error]; [Error]; [Reduce 2]; [Error]; [Reduce 2] |];
     [| [Error]; [Error]; [Error]; [Shift 4]; [Error]; [Error] |];
     [| [Error]; [Error]; [Error]; [Shift 4]; [Error]; [Error] |];
     [| [Error]; [Error]; [Error]; [Shift 4]; [Error]; [Error] |]; |]
let tables = 
  {StartIdx=startKernelIdxs
   SymbolIdx=symbolIdx
   GotoTable=gotoTable
   ActionTable=actionTable
   IsStart=isStart
   ProdToNTerm=prodToNTerm}
